### ISSUE TITLE
Autoscaling approach for queue overload

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#11]
Hi =)

awesome project and thx for making it public!!! <3

I have a question about auto-scaling. 
We are testing pg-boss at the moment and everything looks fine, just the scaling part is a little bit hard. What is if there are more jobs in the queue as the worker can handle?

Our old setup on Amazon AWS: 
App server publishes a notification(==job) to SNS -> SQS -> and a worker in beanstalk receives every job. If there are too much jobs it will auto-add new instances (scale).

We would now replace SNS/SQS with pg-boss to be more independent from AWS.
My first approach was to add a other "cron-like job" which checks the queue size every x min - and if there are too many unhandled jobs - it triggers a beanstalk upscale event.

Do you have any approach how to handle a queue overload?

**Comment by timgit** [comment]
Hey there @phips28!  You're welcome, and thank you as well.  That's a fantastic use case you have, and it got me thinking about how I could expose this via the API.  Since pg-boss is an event emitter, I think it would make the most sense to add a config setting for monitoring based on your desired threshold and then just wait for that event.

Is that sort of what you had in mind?

**Comment by phips28** [comment]
yes that would something I had in mind.

I think about different types of threshold triggers:
e.g. 
- a job should not wait in the queue (untouched) for more than 10sec.
- if pg-boss recognize a linear rise of more created jobs than finished trigger
- ... something else from your side?

And I guess we need something more than just trigger the event. It should only trigger once the upper threshold reached (and hold for x time) and should trigger again when the threshold is in the "safe" area.

**Comment by phips28** [comment]
news on that?

**Comment by timgit** [comment]
No news ha ha. Now that I've shipped 1.0, I can devote more time to thinking about this one.  I have a couple ideas on an implementation, but no code to show for it.  😉  If you have some queries you've written against the job table to address this so far, I'm interested in what you've come up with.  

Whatever it becomes, I'm thinking it should be opt-in and a bit more of a generic monitoring and analytics config.  For example, you would use it for autoscale, but someone else could use it just for metrics and reporting.

**Comment by timgit** [comment]
@phips28 I'd like your feedback on the state monitoring I just pushed to the 1.2 branch

**Comment by timgit** [comment]
Released with 2.0.0
