### ISSUE TITLE
Options modified by manager functions

### ISSUE THREAD

**Issue by OlivierKamers** [timgit/pg-boss#112]
When passing options to for example `publishOnce`, the options object is not copied before modifying it, resulting in some strange behaviour.
I'm trying to add tests for our system using sinon and a spy on our wrapper to `publishOnce` to assert that it is called with some specific options. 
However the assertion fails because it thinks it was called with an options object that also has the `singletonKey` key, even though it was called with the correct options. This is caused by the mutation of the options object later on here: https://github.com/timgit/pg-boss/blob/master/src/manager.js#L152
The same behaviour is found in the other publish functions.
If you agree that this should be changed I see two possible solutions (which I'd be willing to make a PR for):
* Create a clone in `Attorney.checkPublishArgs`
* Create clones in each publish function

**Comment by timgit** [comment]
I think it makes the most sense to clone the objects in Attorney after looking over it again. Seems like a good idea at this time, at least. ;)

**Comment by timgit** [comment]
Included in 3.2.1
