### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by chrisjensen** [timgit/pg-boss#122]
Apologies that this is not an issue, but I couldn't find another avenue to express this.
We've been using pgboss in production for over a year now and we've never had to debug or maintain it in any way. It's well documented, we've never had to peer into the code base to figure out if something is working the way we think it is. It just works.
It's been great both from a reliability perspective and from not having to add more tech to our stack in order to get background jobs. We just publish jobs to the queue and it's been 100% reliable.
Thanks for building this Tim.

**Comment by timgit** [comment]
Thanks Chris. I appreciate you taking the time to write that. Good to hear!

**Comment by terehov** [comment]
Nice idea to thank in a ticket. I couldn’t agree more. 
Thank you Tim!

**Comment by koskimas** [comment]
I would also like to express my gratitude :bowing_man: This library is just awesome! Great quality, never had a problem and even though there's no need to read the code, reading it makes me happy :smile:

**Comment by seeden** [comment]
Thanks @timgit . I have started to use your library today and it is working great.

**Comment by mrmurphy** [comment]
Me, too! We've been using it for months now.
