### ISSUE TITLE
Publish-only instance of boss

### ISSUE THREAD

**Issue by jrf0110** [timgit/pg-boss#124]
I noticed that my web server's boss instance (that's only used for publishing) is periodically polling the database. I'm guessing this is because all instances of PgBoss will act as a worker.

Is there a way to create a _publish-only_ instance of Boss? If not, I'd be happy to contribute a PR that looks something like:

```javascript
const boss = new PgBoss({
  publishOnly: true,
})
```

**Comment by timgit** [comment]
This sounds like a `start()` vs. `connect()` issue perhaps.  I'd have to see more of your bootstrapping code to confirm, but it sounds like you're using `start()` and potentially `subscribe()` in your api.  Also, please included the polling in question that you've detected.

**Comment by jrf0110** [comment]
Hey, Tim. Sorry I've been out on vacation. You're totally right! I thought I had tried both, but I was mistaken.

Thanks!
