### ISSUE TITLE
Unable to iterate the job

### ISSUE THREAD

**Issue by princesinha19** [timgit/pg-boss#127]
When calling subscribe or fetch function, it cancels the job. 
I have created a queue and inserting the jobs using publish queue method after that I want to iterate all job in the queue and want to perform a certain action on a certain condition.

So, I am unable to do that. When I call fetch it shows me only 1 job and then, again calling the function removes the job from the queue.

Please help.

**Comment by timgit** [comment]
Both `fetch()` and `subscribe()` (which uses `fetch()` internally) work by marking a job in the queue as active.  At this point, it can't be fetched again, which is the intention of the queue, but it will expire if you don't mark it as completed or failed within an expiration window. The only way a job can enter 'cancelled' state is explicitly calling `cancel()`.

I'm not sure what your use case is or what you're expecting to happen, but this is a common queueing concept and not something unique to pg-boss.
