### ISSUE TITLE
What are you doing with "expired" jobs?

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#13]
Hi, 

if jobs are failing (however) they get retried (depending on the config, in my case 2 times) and getting the state "expired". 
What do you use to track these "expired" jobs? or do you auto delete them somehow?

**Comment by timgit** [comment]
Currently they go to limbo and are not reachable by the archiver.  This has been fixed and will be released in 0.6.0.  When that occurs, expired jobs will be archived (deleted) just like completed jobs.

**Comment by phips28** [comment]
when do you release?

**Comment by timgit** [comment]
I was hoping to finish testing the schema migration this week and ship with a beta tag so I can get feedback in regards to #10

**Comment by timgit** [comment]
Instead of a 0.6.0 release, I decided to roll this into a 1.0.0. 😀   I'll leave it in beta for a week or so and then release after more testing.

**Comment by phips28** [comment]
So I have nothing to change in my code right?

"expired" just get deleted?

**Comment by timgit** [comment]
Yes
