### ISSUE TITLE
expireIn vs other options

### ISSUE THREAD

**Issue by ngocdaothanh** [timgit/pg-boss#130]
https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#job-expiration-options says:

```
expireCheckIntervalMinutes, int
Default: 1. interval to expire jobs in minutes, must be >=1
```

But https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#job-expiration says:

```
expireIn, string, PostgreSQL interval
Default: 15 minutes
```

Is it 1 or 15 minutes? I guess the latter section is wrong (old doc)?

**Comment by ngocdaothanh** [comment]
Ah, now I understand that `expireCheckInterval*` is the interval for checking, and `expireIn` is for the expiration length.

But please put them close together in one section in the doc.

**Comment by timgit** [comment]
Thanks for the feedback.  I'm relying on the TOC for organizing them by config location and use cases 
![image](https://user-images.githubusercontent.com/656974/66539082-82d9bd00-eaec-11e9-93ad-d5769b598691.png)
