### ISSUE TITLE
Should expired jobs be retried?

### ISSUE THREAD

**Issue by ngocdaothanh** [timgit/pg-boss#132]
Can you improve the doc to explain more about expired jobs?

* As I understand, they are jobs that run for too long and don't give out success or failure result.
* From #13, it seems that expired jobs will simply be ignored?

I think there should be an option to specify whether they should be retried, to have the "at least once" semantic:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

Example use case:
* There are 2 machines processing the jobs.
* One machine takes a job and run, but it crashes (maybe the reason is not related to the job, like electric power failure).
* After the expiration time (visibility timeout), the other machine should can take over the expired job (or when the crashing machine recovers, it can rerun the job).

**Comment by timgit** [comment]
#13 was opened years ago and has been resolved in recent releases.  If a job expires, it's considered failed and you will see this in an `onComplete()` subscription so you can react to it.
