### ISSUE TITLE
Using the result of a job

### ISSUE THREAD

**Issue by roemhildtg** [timgit/pg-boss#134]
I have a node server that is creating jobs and returning the Job ID as a response. I can then use that Job ID to query the current status of the record:

```
GET /job/xxx-xxx-xxxx

// returns
{
    "id": "xxx-xxx-xxxx",
    "status": "created",
     ...job details
}
```

But what if I want to retrieve the actual response of the job? For example, one job returns a result like:
```json
{
    "id": "report-xxx-xxx.pdf"
}
```

 I know these results get stored but they have a new unique ID and a new job queue name. Just curious if you had run into this sort of scenario and how you'd recommend solving it. 

So far my only idea has been to do another query on the database in my GET request handler where `data LIKE "%xxx-xxx-xxxx%"` and then add that to the job response. 

Here's an example working for context:

```js
// GET /job/xxx-xxx-xxxx

    async get (id, params) {
        const original = await this.db.get(id, params);
        const completed = await this.db.Model
            .raw(`SELECT * FROM ${JOB_SCHEMA}.${JOB_TABLE}
            WHERE data->'request'->>'id' = ?`, [id]);

        return {
            ...original,
            result: getByDot(completed, 'rows.0.data.response'),
        };
    }
```

**Comment by timgit** [comment]
You should be able to use `fetchCompleted(queue)` for this
