### ISSUE TITLE
How to immediately re-queue failed singleton job?

### ISSUE THREAD

**Issue by chrisjensen** [timgit/pg-boss#137]
We have jobs that we want to ensure only 1 active job is ever queued.
For some longer running jobs, we abort them if the worker gets a SIGHUP (ie the server is cycling containers) so they can cleanly shutdown before the process is terminated.
Ideally we'd like to restart them immediately in another worker by re-publishing the job.

I thought we could use a singleton key for this, but it seems to applied to complete jobs too so the job can't be republished until archive runs on the table.

It seems to me like singleton keys can't be used to solve this problem but wanted to check if there was a solution I'd missed.

**Comment by timgit** [comment]
Have you considered adding a retry configuration on the job and then just fail it along with your abort process?

**Comment by fellars** [comment]
> but it seems to applied to complete jobs too so the job can't be republished until archive runs on the table.

is that true?  i am testing it out and doesn't seem to be the case. I'm able to re-add with a singletonkey if the job is completed but not yet archived. or am i doing it wrong?

**Comment by timgit** [comment]
These tests show how it works
https://github.com/timgit/pg-boss/blob/master/test/singletonTest.js
