### ISSUE TITLE
Priorize jobs

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#14]
Idea: wouldnt it be cool to give jobs a higher priority?

Now you do a simple FIFO by createdOn date.

Usecase: 
I add jobs for doing some background calculations (non-critical)
I add jobs for sending push notifications to users (critical)

Now I would like to add a "high" priority to the push job. 

This could be easy solved by adding an `priority int` field and change the order by in the nextJob()

Do you think this is useful?

**Comment by phips28** [comment]
I am using a different approach. 
We are publishing and subscribe to "work" as job name.
And the real job name/todo name is in the payload.
The jobs are in a folder like `jobs/SendNotification.js` and it will be automatically required and executed with the rest of the payload.

This usage is easier for everyone in the tech team, because if you would have 100 jobs, you would need 100 worker subscribed to the different job names, means 100 DB connections. (or if you have teamSize: 3 => 300 DB connections)
And maintaining these 100 worker is also bad if you hardcode the subscribe for each.

**Comment by timgit** [comment]
the pg module uses connection pooling, so it shouldn't be a concern from a db connection perspective.  I actually use a perf test that has teamSize set to1000 and it finishes processing in 700ms.

If you're still determined to group the jobs like that, you could also consider subscribing by priority.  Such as `work` and `workHigh` or `workLow` for higher and lower priority intervals and configs, for example.

**Comment by phips28** [comment]
Ok, I dont think the connection pool is working for me.
I have 2 server with worker running and teamSize: 6.

My database shows me there are 12 connections:
`SELECT * FROM pg_stat_activity;`
https://www.dropbox.com/s/ctx2d3zpbificge/Screenshot%202017-03-01%2009.59.50.png?dl=0
(using the "application_name" in the db config to see it in the postgres activity)

Ok I keep this "workaround" in mind but I am not going to implement it now ;)

**Comment by timgit** [comment]
Just to make sure I'm understanding, you have 2 `subscribe` handlers, each with the teamSize option set to 6, each on a separate server both connected to the same pg instance?  If that's the case, then you should have not more than 20 connections, correct?

**Comment by phips28** [comment]
I have exactly 12 connection, the marked one in the screenshot. With pgboss in the name.

**Comment by timgit** [comment]
That seems correct based upon a 2 pgboss instances.  What I meant by "not more than 20" is since each pgboss instance should not use more than 10 connections.

**Comment by timgit** [comment]
@phips28 I just pushed `1.0.0-beta2` to address more fine-grained control over connection pooling.  After you brought this up, it made me realize I could do far better in regards to connection management and also make it configurable. 

I don't have docs for this of course, but you can now add a `poolSize` property to the config object in the constructor in order to have a "not to exceed" connection count no matter the `teamSize` setting.

**Comment by timgit** [comment]
@phips28 is this issue primarily regarding the connection mgmt?  ok to close, or did you still have an ask regading your original post?

**Comment by phips28** [comment]
pool its fine.

priorize jobs would be interesting for me ;) maybe I have time to do a PR.

**Comment by timgit** [comment]
@phips28 I have a preview of this in the 1.2 branch.   You might as well check this out while you're checking out #11

**Comment by timgit** [comment]
Released with 2.0.0
