### ISSUE TITLE
Typescript: monitorStateInterval* missing

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#143]
Hello,
just a little heads up.

The options: `monitorStateInterval*` are missing in `types`.

`type ConstructorOptions = DatabaseOptions & JobCreationOptions & JobFetchOptions & JobExpirationOptions & JobArchiveOptions;`

**Comment by timgit** [comment]
Thanks.  I have this corrected in the upcoming 4.0 release.  PR #142

**Comment by phips28** [comment]
sounds good :)
