### ISSUE TITLE
Poll: Max ttl for jobs 

### ISSUE THREAD

**Issue by timgit** [timgit/pg-boss#144]
I have the need of purging jobs that were created and for whatever reason were abandoned and will never be picked up. 

I’m imagining this as a constructor option using an int for number of days. 

Since there could be a large range of allowable timelines across all queues, I’m thinking this value should be very generous, along the lines of 90 days before eviction into the archive. It would then have the normal retention policy in the archive before permanent deletion. 

I’m also considering adding overrides to make this queue-specific, but think of that as a way to evict sooner, since there needs to be a maximum value enforced eventually to prevent manual maintenance operations. 

Do you guys think 90 days is a good default?

**Comment by mshwery** [comment]
`expireIn` seems to hold the semantics I would expect for this behavior – e.g. if you don't complete this job by N interval from when it was created, it should expire. But since that job configuration name is taken, something like `maxTtl` or just `ttl` could work fine. I think we'll need additional documentation to disambiguate the two options.

Any reason not to use pg intervals like the we do with many config options already?

**Comment by timgit** [comment]
It actually never occurred to me until your comment that this could be a point of confustion, but after reading through all the docs again, I now realize I've always assumed that everyone knew what "expired" meant. The docs have several implicit explanations and behaviors such as "retries on expiration", but I never explicitly define it as "a job is eligible for expiration once it enters `active` state". What I'm proposing in this issue is something just like expireIn but for the `created` state.

I do agree that it would be consistent to stick with pg intervals, but my biggest issue with them is the lack of a pre-flight parse and validation in the library before "sending it" to postgres and letting it throw as a more generic connection error. In fact, given the number of breaking changes included in 4.0, I'm now wondering if I should just go ahead and break with all pg interval usage in favor of specific int config values that can be validated pre-flight.
