### ISSUE TITLE
Readiness handling, exposing isReady

### ISSUE THREAD

**Issue by leventov** [timgit/pg-boss#146]
pg-boss rejects normal requests (such as `publish()` or `subscribe()`) if pgBoss isn't ready yet:
https://github.com/timgit/pg-boss/blob/0dbc2d2628d96df343b3f6f3e1cd4afe44bd9dd2/src/index.js#L59-L84

This is inconvenient during integration testing because we have to wait for several seconds before starting commands or else we don't have expected results.

I think it makes more sense to check that pg-boss is *started* and *await* if it is not ready yet.

Also, it would be useful to expose `isReady()` in pg-boss API so that it could be used in readiness checks logic.

**Comment by timgit** [comment]
Are you not awaiting start()? Also, given you have a testing use case, have you looked at how the test suite does this?

**Comment by leventov** [comment]
Indeed, there was a problem in jest `beforeAll()` setup, thanks.

Nevertheless, `isReady()` would be valuable anyway for readiness checks implementation.
