### ISSUE TITLE
Default job retries

### ISSUE THREAD

**Issue by bartvanremortele** [timgit/pg-boss#149]
Hi,

First of all let me start by saying you did an awesome job building this. 

I have a feature request concerning job retries. Currently it seems that it is not possible to specify a default value for job retries through the constructor and it is only possible by passing them through the publish method. 

I believe it would be a great feature addition to be able to set the retries to a sensible default instead of defaulting it to off. 

Thanks

**Comment by timgit** [comment]
Thanks for the feedback!  This should be included in 4.0 release that's in flight
