### ISSUE TITLE
Couldn't understand how throttling/rate-limiter works

### ISSUE THREAD

**Issue by gijo-varghese** [timgit/pg-boss#152]
I'm building a web scraper. Basically, the task of a worker is to download a page.

Each website needs to be downloaded at different rate limits. For example, website `A` must be downloaded at max 3 concurrent pages. website `B` at max 5 concurrent pages and website `C` at max 10 concurrent pages. 

There might be 10+ workers (autoscaling nodes) and each website will have its own queue.

I guess the limits should be set in `publish` right? I'm a little confused about what should be the values for `singletonSeconds`, `singletonNextSlot` and `singletonKey` to achieve this. Can you pls help?

**Comment by timgit** [comment]
All rate limiting features are on the publish side and control how often jobs are allowed to be created into queues. This controls inbound data, but your use cases sound like you also need to control outbound concurrency, which is outside the scope of what the queue could provide you.

**Comment by gijo-varghese** [comment]
@timgit Ok. Thanks for the reply.

Can you recommend me any other queues which works with NodeJS and support this requirement?

**Comment by timgit** [comment]
You could use the `batchSize` option in your subscription to fetch jobs in an array all at once, then use Promise.all() with them to fan out in parallel. That's probably the easiest way to do it.

**Comment by gijo-varghese** [comment]
but if I put `bazeSize: 3` and I've 3 workers, then total 9 tasks will be executed in parallel right? 

Since I'll have horizontal scaling, I can't predict the no. of workers

**Comment by gijo-varghese** [comment]
Ok. Did you mean `batchSize` in fetch/ https://github.com/timgit/pg-boss/blob/master/docs/usage.md#fetch

**Comment by timgit** [comment]
batchSize is in both fetch and subscribe: https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#subscribe-options

In regards to horizontal scaling, I don’t have enough info to make any recommendations, but it does sound like you have 2 conflicting concerns there. For example, you have a scale out use case which hypothetically could be a large number of workers. However, it seems you have a hard limit on the rate of concurrency, which sounds like it hurts you to have too many workers. 

For example, if you have 1 worker and you’re already hitting your rate limit, adding another worker causes you a problem of exceeding your limit. One solution would be to track your job concurrency in another table in your database and then check it before you do a fetch ( not subscribe ). You could use something like transactional advisory locking in postgres to handle distribution, but again, these are all just ideas and not recommendations.

**Comment by gijo-varghese** [comment]
Got it. So far Google Cloud Tasks seems to have this feature. We can set the max concurrent tasks while publishing. Listeners will be basically HTTP endpoints, where they've to respond with 200 when the task is done. Horizontal scaling also works really well.

One drawback is I'll have to stick with Google Cloud. I'm also thinking about building something with Postgres locks.

Thanks anyway.
