### ISSUE TITLE
Rewrite project with TypeScript

### ISSUE THREAD

**Issue by Shinigami92** [timgit/pg-boss#158]
I was emailed by someone who said I could help rewrite `pg-boss` into TypeScript

I am writing such changes for my personal knowledge and to support the growth of the TypeScript community
The project only has to meet a few criteria

1. It must be open source (✅)
2. It must be licensed under MIT or Apache (✅)
3. It must be a non-profit repo (donations are fine) (✅)

I already helped rewritten [node-pg-migrate](https://github.com/salsita/node-pg-migrate) and helped [nteract](https://github.com/nteract/nteract)

---

Rough overview of what would change:

1. Setup a `tsconfig.json`
2. Rewrite everything in `src` to `.ts`
3. Use the typedefs from the file `types.d.ts` and then delete this file afterwards
4. Create a build step that creates a `dist` folder
   This is the new folder that will be published with npm

**Comment by Shinigami92** [comment]
Oh didn't looked into PRs ^^ -> Someone already started it: https://github.com/timgit/pg-boss/pull/156

**Comment by moltar** [comment]
> I was emailed by someone who said I could help rewrite pg-boss into TypeScript

It was also me who emailed :)
