### ISSUE TITLE
Is pg_boss suitable for a scheduler-like mechanism

### ISSUE THREAD

**Issue by Globik** [timgit/pg-boss#16]
Hi, just wondering wether the pg-boss is suitable for a scheduler-like mechanism? Say, job.publish in 30 minutes.

**Comment by phips28** [comment]
I would say yes ;)

**Comment by timgit** [comment]
@Globik, you would be interested in `{startIn: '30 minutes'}` passed as options during `publish()` methinks

**Comment by Globik** [comment]
function ready() {
    boss.publish('work', {startIn: '30 minutes', message: 'stuff'})
        .then(jobId => console.log(`sent job ${jobId}`));

**Comment by Globik** [comment]
1. startIn must be integer 60*60*3600 or human readable 'in twenty minutes'?
2. Is table's field 'singletonOn' for the option 'startIn'?

**Comment by timgit** [comment]
1. `startIn` is a string which conforms to a PostgreSQL interval.  Docs: https://github.com/timgit/pg-boss/wiki/Configuration#publish-options
2. No. `singletonOn` is for throttling

**Comment by Globik** [comment]
Thank you very much for your explanations. One can close this issue. Very nice job.

**Comment by timgit** [comment]
Thanks

**Comment by Globik** [comment]
startIn does not work, startAfter is ok in version 3.0
