### ISSUE TITLE
Issue with migrating from version 2 to version 4

### ISSUE THREAD

**Issue by nabilzhafri** [timgit/pg-boss#161]
Hi, I was trying to migrate from v2 to v4, however I noticed a couple of issues, where some indexes and some columns are missing. i.e. index job_name, column startAfter...

Then I noticed in the migration file, it's missing migrations for version 8 and below, which seems to be required to migrate from version 2 to 4. Any reason why they've been removed?

I know I could migrate to v3 first then to v4, but since I'm doing major upgrades to my backend platform, I would like to do it in one shot if possible.

**Comment by timgit** [comment]
I'll restore the migrations in v 4.1. I have this released in beta right now.

```
npm i pg-boss@4.1.0-beta1
```
