### ISSUE TITLE
schema creation on .start() error

### ISSUE THREAD

**Issue by EvertEt** [timgit/pg-boss#164]
I have come across some weird behaviour which I am not too sure about as to why it happens:

In our tests we clear the pg-boss tables in a `beforeEach` like:
```
const PG_BOSS_TABLES = ["archive", "job"];
await Promise.all(PG_BOSS_TABLES.map((table: string): Promise<void> => Bookshelf.knex.withSchema("pgboss").table(table).truncate()));
```

On my dev machine I could get this to fail by deleting the `pgboss` schema and running a test, causing it to error with `error: truncate "pgboss"."archive" restart identity - schema "pgboss" does not exist`.

Therefor I added an `await pgboss` before the `Promise.all` truncate where `pgboss` is `bossInstance.start()` chained with another then subscribing all our jobs.
This resolves the problem on my local machine but not on our CI (bitbucket pipelines, node14.1.0 image)
On our CI it fails with the exact same message:
```
     error: truncate "pgboss"."archive" restart identity - schema "pgboss" does not exist
      at Connection.parseE (node_modules/pg/lib/connection.js:581:48)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:380:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:116:22)
      at Socket.EventEmitter.emit (domain.js:485:12)
      at addChunk (_stream_readable.js:300:12)
      at readableAddChunk (_stream_readable.js:276:9)
      at Socket.Readable.push (_stream_readable.js:217:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

Do you have any idea what might be causing this? Should the schema not be created after awaiting the start promise?

Thanks in advance

PS 
```
    await pgboss;
    console.log(await Bookshelf.knex.raw("select schema_name from information_schema.schemata;"));
    await Promise.all(PG_BOSS_TABLES.map((table: string): Promise<void> => Bookshelf.knex.withSchema("pgboss").table(table).truncate()));
```
Indeed logs the pgboss schema locally but not on our CI.

**Comment by timgit** [comment]
Sounds like you need a global `before()` to create the schema.  There are lots of examples of this in the test suite (https://github.com/timgit/pg-boss/tree/master/test).

**Comment by timgit** [comment]
Here's a recent test run: https://travis-ci.org/github/timgit/pg-boss/jobs/671458457

**Comment by EvertEt** [comment]
By the way, it happened during the upgrade from 3.1.6 to 4.1.0.

We also have a global before like below which I think you are describing?
```
before(async () => {
    await pgboss;
});
```
where `pgboss` is
```
export default bossInstance.start()
```

**Comment by timgit** [comment]
If you want to isolate each test with installation and uninstallation of pgboss, I suggest you customize the schema per-test.  I do this in the test suite to make sure 1 test doesn't stomp on another.  Not sure if this is happening in your suite, but it helps me identify errors in mine if I forget to issue a `stop()`, for example.

**Comment by EvertEt** [comment]
The problem appears on the very first test (even if we just run a single test) so I have the feeling it is not related to the cleanup. Our tests on the CI are run on a clean, empty DB but the pgboss schema should be there when awaiting the start command right?

**Comment by EvertEt** [comment]
I was able to give a bit cleaner example (not in our tests) but running the following script
```
import Bookshelf from "./config/database.ts";
import pgboss from "./config/pg-boss";

async function run() {
    await pgboss;
    console.log((await Bookshelf.knex.raw("select schema_name from information_schema.schemata;")).rows);
}
run();
setTimeout(() => process.exit(0), 1000);
```
which logs show that the pgboss schema is not created yet
```
[
  { schema_name: 'pg_toast' },
  { schema_name: 'pg_temp_1' },
  { schema_name: 'pg_toast_temp_1' },
  { schema_name: 'pg_catalog' },
  { schema_name: 'public' },
  { schema_name: 'information_schema' }
]
```
where the `pg-boss` file contains the following
```
const bossInstance = new PgBoss({
    host: config.db_host,
    database: config.db_name,
    user: config.db_user,
    password: config.db_password,
    port: config.db_port || 5432,
});

bossInstance.on("error", ErrorHandler.captureException);

export default bossInstance.start();
```

**Comment by timgit** [comment]
Try awaiting pgboss.stop() after each test run, too, to make sure the errors aren’t from the maintenance ops running in the background. There is an option you can pass to the constructor as well which that will disable maintenance ops

**Comment by EvertEt** [comment]
Since it happens at the very beginning and also in the example above, I believe the stop would not change much. I did find an error about pgcrypto in the logs. Installing it seems to solve the problem. I will close this issue after some more testing.
```
2020-05-02 18:36:49.641 UTC [63] ERROR:  function gen_random_uuid() does not exist at character 404
2020-05-02 18:36:49.641 UTC [63] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2020-05-02 18:36:49.641 UTC [63] STATEMENT:  BEGIN;
	SELECT pg_advisory_xact_lock(1337968055000);
	
	    CREATE SCHEMA pgboss
	  ;
	
	    CREATE TABLE pgboss.version (
	      version int primary key
	    )
	  ;
	
	    CREATE TYPE pgboss.job_state AS ENUM (
	      'created',
	      'retry',
	      'active',
	      'completed',
	      'expired',
	      'cancelled',
	      'failed'
	    )
	  ;
	
	    CREATE TABLE pgboss.job (
	      id uuid primary key not null default gen_random_uuid(),
	      name text not null,
	      priority integer not null default(0),
	      data jsonb,
	      state pgboss.job_state not null default('created'),
	      retryLimit integer not null default(0),
	      retryCount integer not null default(0),
	      retryDelay integer not null default(0),
	      retryBackoff boolean not null default false,
	      startAfter timestamp with time zone not null default now(),
	      startedOn timestamp with time zone,
	      singletonKey text,
	      singletonOn timestamp without time zone,
	      expireIn interval not null default interval '15 minutes',
	      createdOn timestamp with time zone not null default now(),
	      completedOn timestamp with time zone,
	      keepUntil timestamp with time zone NOT NULL default now() + interval '30 days'
	    )
	  ;
	CREATE TABLE pgboss.archive (LIKE pgboss.job);
	CREATE INDEX archive_id_idx ON pgboss.archive(id);
	ALTER TABLE pgboss.archive ADD archivedOn timestamptz NOT NULL DEFAULT now();
	CREATE INDEX archive_archivedon_idx ON pgboss.archive(archivedon);
	
	    CREATE INDEX job_name ON pgboss.job (name text_pattern_ops)
	  ;
	
	    CREATE UNIQUE INDEX job_singletonOn ON pgboss.job (name, singletonOn) WHERE state < 'expired' AND singletonKey IS NULL
	  ;
	
	    CREATE UNIQUE INDEX job_singletonKeyOn ON pgboss.job (name, singletonOn, singletonKey) WHERE state < 'expired'
	  ;
	
	    CREATE UNIQUE INDEX job_singletonKey ON pgboss.job (name, singletonKey) WHERE state < 'completed' AND singletonOn IS NULL
	  ;
	INSERT INTO pgboss.version(version) VALUES ('12');
	COMMIT;
```

Should pgboss.start error if this extension is not available?
Was this also required before version 4?

**Comment by timgit** [comment]
I removed pgcrypto from the schema creation in v4 since it requires superuser privilege not available to typical run time user configurations.

**Comment by EvertEt** [comment]
I understand, thanks a lot! 
This is clearly my own mistake as it is indicated clearly in the changelog.
The only weird thing is that .start() seems to silently resolve without creating the schema if the extension is not available, maybe this is a possible improvement?

**Comment by timgit** [comment]
start() does throw an error properly.  I just wrote a test for this to confirm:
https://github.com/timgit/pg-boss/blob/93f88584582f4c5020d25568974360df7173a906/test/configTest.js#L60-L80

Test run:
https://travis-ci.org/github/timgit/pg-boss/jobs/682493334#L534

**Comment by EvertEt** [comment]
You are correct once again! Our testing setup hid some errors as we were expecting them in some tests. Thanks again
