### ISSUE TITLE
Getting job metadata like startafter on subscribe?

### ISSUE THREAD

**Issue by kevboh** [timgit/pg-boss#166]
Hi! We're in the processing of instrumenting our pg-boss instance, and one of the metrics we're interested in is the span of time between a job's `startafter` column and the time it was actually dequeued and initiated. It looks like only id, name, and data are returned for subscribed jobs—is there any way to get other data out beyond manually selecting for it on `pgboss.job` once a job is dequeued?

**Comment by timgit** [comment]
All of this data is in the payload of an onComplete() subscription.  Is that an option?

**Comment by kevboh** [comment]
Unfortunately it's not, purely due to the way our tracing is configured—we need that info up-front so it can sent to our observation service alongside the rest of the "job has begun" event.

I've added this in a fork as it's something we needed pretty urgently, but if you think this is worthwhile I can PR either specifically this change or a more general config option can opt in to extra columns when fetching the next job.

**Comment by timgit** [comment]
I like this idea, and definitely think it's worth a general config option. Can you post a link to your fork here if it's public?

**Comment by kevboh** [comment]
Here's the only change in the fork: https://github.com/postlight/pg-boss/commit/1d53ea47dec635da9a2beda210d892b780f8b05b

Thinking about it over night, I think the API I'd prefer is either a single boolean `extendedSubscription` (or similar, I'm sure you'd have a better name) that opts in to the entire job row for `subscribe`, or a more fine-grained approach were you can pass in an array of column names you want, it makes sure they're valid, and then appends them to the query. I'd be happy to PR either approach.

**Comment by kevboh** [comment]
I suppose it's also worth noting that we're doing this to be able to calculate `startedon - startafter`, which is something pg-boss itself could calculate and return in the API, but I think the other approaches are probably more useful for others.

**Comment by kevboh** [comment]
Just to follow up—I can probably submit this PR this week. Just let me know how you'd prefer the API to look like.

**Comment by timgit** [comment]
For now I think that it would be more simple to return all columns using a boolean config option added to fetch and subscribe. Maybe something like `includeMetadata`  What do you think?

**Comment by kevboh** [comment]
Yeah, I’m into it. I hope to be able to PR that soon.
