### ISSUE TITLE
How to use together with routing system

### ISSUE THREAD

**Issue by Globik** [timgit/pg-boss#17]
Hi, I would be to know how to use pg-boss with routing in an typical application.
The problem that the start function called only ones. But the router calls are many times.
boss.start();
Router.get('/index', function(res,req){
boss.publish('work') ??...;
boss.subscribe(...)
});
Or should be boss.start() within a router path?
Or should I create a job within a router path using connect - disconnect API?

**Comment by Globik** [comment]
Or should be elswhere the trigger functions and perfoming pg_notify events?
Let's say I have some advertisment block on a site and I want to in a short period enable it with boss.publish. If I am inserting into the advertisment table some value, trigger works and send signal to pg_subscriber and then should be work boss.publish?

**Comment by Globik** [comment]
When I call boss.connect() then where should I call boss.disconnect()?

**Comment by timgit** [comment]
@Globik You'll want to keep one instance of pg-boss running for the duration of your application lifetime, not per request.  What I usually do is delay starting of my router until the start() promise resolves.

Also, I personally use another node instance from `child_process.fork()`, but it's completely up to you where you want to run your subscribers.

btw, you should upgrade to 1.0.0 in order get the pg-pool integration.  You can now set a `poolSize` property in the config when you create your instance.  I haven't had a chance to document this yet, but I will soon.

**Comment by Globik** [comment]
O'key, I will upgrade the pg-boss. It seems me to know how to handle this module. I'll try via pg-notify stuff. Thank you very much. One can close this issue.
