### ISSUE TITLE
Cannot find name 'PostgresInterval'.

### ISSUE THREAD

**Issue by timothyallan** [timgit/pg-boss#170]
Heya, started getting this after a re-install today with 4.3:

node_modules/pg-boss/types.d.ts:144:15 - error TS2304: Cannot find name 'PostgresInterval'.

Assuming it's somehow related to the TypeScript update in the changelog?

**Comment by timgit** [comment]
I pushed an update with the missing type def in 4.3.1

**Comment by timothyallan** [comment]
That'll do it, working well now, thanks!
