### ISSUE TITLE
db parameter can not be used anymore in typescript code

### ISSUE THREAD

**Issue by mlegenhausen** [timgit/pg-boss#175]
#173 introduced a bug where the `db` Parameter can not be specified anymore in the constructor. When you look in the `types.d.ts` file the `Db` interface is not used anywhere.

Following code in the `types.d.ts` solves this issue

```ts
type DatabaseOptions = PoolConfig | { db: Db };
```

**Comment by timgit** [comment]
Included in 4.3.4
