### ISSUE TITLE
boss.schedule is not a function

### ISSUE THREAD

**Issue by AlbertoInsud** [timgit/pg-boss#179]
Hi guys,
i start to use this to do some stuff ( like create folders every day, etc. ).
But when i try use schedule ( await boss.schedule('notification-abc', `0 3 * * *`, null, { tz: 'America/Chicago' }) ), mentioned in your documentation, throw exception 'boss.schedule is not a function'.

Thanks in advance.

**Comment by brianmcd** [comment]
As a quick check, are you using version 5.x of pg-boss? The scheduling functionality was just released, and it's not available on 4.x.

**Comment by AlbertoInsud** [comment]
I use 4.3.4 version. I thought not exist a 5.x version. 
I´ll try get it.

Thanks in advance.

**Comment by AlbertoInsud** [comment]
Nice!!.
Was release yesterday and i didn't see before write this.
Thanks for all.
