### ISSUE TITLE
Every launch, repeat once

### ISSUE THREAD

**Issue by AlbertoInsud** [timgit/pg-boss#180]
Hi, i don not know what i do wrong.

I try for every run, create a file but cannot do it.

My code is this:

       await boss.start();

        let jobId = await boss.publish(queue, { param1: 'foo' })

        await boss.schedule(queue, `*/15 * * * *`, null, { tz: 'Europe/Madrid' });
        
        await boss.subscribe(queue, options, job =>{
            console.log(JSON.stringify(job.data));
            createFile(job.data);
        });`

Thanks in advance.

**Comment by timgit** [comment]
In your example, it appears you should be seeing a console log since you manually publish ahead of your subscribe.  Also, your subscribe handler should be async or return a promise to automatically mark the job as completed.

**Comment by AlbertoInsud** [comment]
Hi again,
i think i not explain well.

Every time start the code just launch one time and then will not do any more.
Past friday i has playing with some options and i found this:

`const options = { teamSize: 2, teamConcurrency: 4 }`

with this, my subscribe repeat 4 times and no more.
the question is, can i do a scheduler for ever until i say 'stop'?

Thanks in advance.

**Comment by timgit** [comment]
Here's an example of what I mentioned in my previous comment

```js
    await boss.start();

    // not relevant to the schedule
    //let jobId = await boss.publish(queue, { param1: 'foo' })

    await boss.schedule(queue, `*/15 * * * *`, null, { tz: 'Europe/Madrid' });
    
    // added async/await to subscribe
    await boss.subscribe(queue, options, async job => {    
    //await boss.subscribe(queue, options, job =>{
        console.log(JSON.stringify(job.data));
        await createFile(job.data);
        //createFile(job.data);
    });
```

**Comment by AlbertoInsud** [comment]
At this time, like that i have my code.

How i mentioned, only execute "x" times (teamconcurrency option) and i want the job execute all the time until i unsubscribe the schedule.

It´s possible?

**Comment by timgit** [comment]
It doesn't sound like you need `teamConcurrency` if you only want to execute this once per cron interval.  Also, if you want an "every x minutes" cron, you don't need the `tz` option either.  It will run at the same interval as UTC.

Use the following as a test, and it will run once a minute.

```js
await boss.subscribe(queue, async job => { console.log(`job ${job.id} received`) });
await boss.schedule(queue, '* * * * *')    
```

After running this, check your pgboss.job and/or pgboss.archive table and you should see each job being created by the scheduler.

**Comment by AlbertoInsud** [comment]
Thanks!!! 
i thought "options" in "subscribe" method cannot be omitted.
In all examples, i could see, when use subscribe always use "options" like a null.
