### ISSUE TITLE
Is possible pause a schedule?

### ISSUE THREAD

**Issue by AlbertoInsud** [timgit/pg-boss#181]
Hi again,

i´m sorry if i irritating you with my questions :P

how it´s possible pause/stop a schedule? i not want delete, only pause.

If i use delete Queue the queue is waiting and remaining all files and then i "active" again it launch all remaining at same time.

Thanks in advance

**Comment by timgit** [comment]
You can use `unschedule(name)` which should result in the same behavior.

**Comment by AlbertoInsud** [comment]
I´ll try, thanks.
