### ISSUE TITLE
Expressjs Example

### ISSUE THREAD

**Issue by saratonite** [timgit/pg-boss#182]
Provide expressjs example

**Comment by timgit** [comment]
The way I've set up express with pg-boss was something like the following.

* GET /jobs?queue=abc&batch=10 = `boss.fetch('abc', 10)`
* POST /jobs?queue=abc  = `boss.publish('abc', request.body)`
* POST /jobs/:id/cancel = `boss.cancel(id)`
* POST /jobs/:id/complete = `boss.complete(id, request.body)`
* POST /jobs/:id/fail = `boss.fail(id, request.body)`
