### ISSUE TITLE
Add config to configure cronMonitorInterval

### ISSUE THREAD

**Issue by davazp** [timgit/pg-boss#186]
I noticed this change recently:

https://github.com/timgit/pg-boss/commit/1069452b0885f1f6c6f11da69b6807d650ba867e#diff-9170079ca86fbde3aae4faa71f1b6746R51

The `cronMonitorInterval` is being set to 60 ms (!!). So it's generating quite a lot of queries.  Did we mean this to be 60 seconds as a default perhaps?  In any case, it would be nice to make it configurable as well.

**Comment by timgit** [comment]
Oh snap!  Good catch.  I just pushed a patch for this in 5.0.7.  I think it's a good idea to force this to 60s because it's a cron processor.  What would you set it to if you could configure it?

**Comment by davazp** [comment]
hm, no I don't have any use case 🙂   60s is good!
