### ISSUE TITLE
Bulk publish

### ISSUE THREAD

**Issue by chrisjensen** [timgit/pg-boss#189]
Would you be open to a PR for publishing multiple jobs at once?
We've got a use case where jobs come in batches. It makes sense to make them discrete jobs for each record in the batch, but it's not ideal to do 1000 seperate insert queries when we could just do one to queue all the jobs.

**Comment by timgit** [comment]
Yes, this is essentially the same request as #47, but perhaps not if the array is large enough, you may not be interested in materializing that in memory. 

Also, before you go off and write all the code, I also have this need in my app.  You can always use `INSERT INTO ... SELECT ... ` or `COPY` directly into the job table if you need the highest load per possible.
