### ISSUE TITLE
Boss subscriber does not work with a disconnection

### ISSUE THREAD

**Issue by Globik** [timgit/pg-boss#19]
Hi,
I'm trying perform a subscriber within ready function. And to publish the work within boss.connection. It's woring without disconnection, but with it not works.
Here is my snippet:

var koa=require('koa');
var PgBoss=require('pg-boss');
var boss=new PgBoss('postgress://globik:null@localhost:5432/postgres');
var app=koa();
boss.start().then(ready).catch(err=>console.log(err));

function ready(){
boss.subscribe('work', (job,done)=>{
console.log(job.name,job.id,job.data);
done().then(()=>console.log('confirmed done'))
})
}	

// trying simulate a router call. Within router path 
boss.connect().then(()=>{
// how many connections can one establish? 10? 20? 100?
console.log('Is connected');
boss.publish('work',{message:'sendPost'},{startIn:"6 seconds"}).then(jobid=>{
console.log(jobid);
boss.disconnect().then(()=>{console.log('Disconnected');});
// boss.subscribe('work') in  the 'ready' function does not work
//without boss.disconnect() - works great
});
});
app.listen(process.env.PORT || 5000)
console.log('port 5000');

Is it normal when I will be using a publisher without disconnection?

**Comment by timgit** [comment]
You need to nest all of your code inside your ready() to wait on the promise to resolve.  Also, you don't need to use `connect()` if you've already run `start()`;  `connect()` is for additional processes for distributed use cases.

**Comment by Globik** [comment]
Thank you for explanation. One can close this issue.
