### ISSUE TITLE
Bluebird

### ISSUE THREAD

**Issue by jrpedrianes** [timgit/pg-boss#191]
Would do you think in remove Bluebird dependency?

In node 10 we already have Promise API supported, also almost all the methods used in the project are in the default implementation.

In the past, we had problems with bluebird and async local storage, that we use in some situations. Exists [cls-bluebird ](https://www.npmjs.com/package/cls-bluebird) but is outdated.

**Comment by jrpedrianes** [comment]
if you deem it appropriate, I can create a PR removing the Bluebird dependency changing the non-standard Promise functions used (delay and map).

**Comment by timgit** [comment]
What would you replace them with? p-map and delay? There are 2 Promise.map() usages, one in manager and 1 in timekeeper.  There's another PR open for converting the manager one to p-queue, so perhaps timekeeper could use p-queue as well.  The test suite has more usages, but those could probably be more easily switched to Promise.all() since there's no concurrency limits

**Comment by jrpedrianes** [comment]
I was thinking in replace all the map usage using an implementation with native Promise.

As the first iteration, I have developed a map implementation that mimics the Bluebirds implementation, and I was thinking to replace the current map usage with this one instead of using p-map, so we have the same behaviour than using Bluebird.

Reviewing the p-map implementation seems that it has a different behaviour with Bluebird, it applies mapper functions in order instead of when any promise is done, as Bluebird implementation does, see:
* https://github.com/sindresorhus/p-map/blob/master/index.js#L73 
* https://github.com/sindresorhus/p-map/blob/master/index.js#L34

If you think that this behaviour change is acceptable I will use p-map in the whole project.

**Comment by timgit** [comment]
I want to see if we can get away with only using p-queue, provided we merge that. Promise.delay can be swapped out with delay, and most if not all other usages in the test suite can be replaced with Promise.all() since they don't need concurrency support.

**Comment by jrpedrianes** [comment]
As first iteration, We can remove bluebird dependency using p-map and delay. That it doesn’t imply biggest changes and then can be applied the change to use of p-map with p-queue. 

In testing, as you comment, we can change Primes.map by Promise.all without problems.

**Comment by timgit** [comment]
My point is that we should wait for the p-queue merge before changing this, given it's not a critical fix.  This will reduce the dependency churn a bit

**Comment by jrpedrianes** [comment]
Oook let me know if you need help to solve this issue
