### ISSUE TITLE
What does retention mean?

### ISSUE THREAD

**Issue by gc** [timgit/pg-boss#192]
Looking in the config, i see this: https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#retention-options

By default its 30 days, judging by the description of it, is this saying its going to delete my jobs/tasks after 30 days?

**Comment by timgit** [comment]
Yes.  This is how long a job can be in the queue in created or retry state before being archived

**Comment by gc** [comment]
Even scheduled jobs that run on a Cron? And what about if you schedule a job to run once in 31 days in the future?

**Comment by timgit** [comment]
When you use `schedule()` an entry is created in a table that is used to evaluate a cron expression to determine if a job should be published.  Retention applies to jobs, not to the schedule entry.  For example, if you were to stop subscribing to a job queue, but some jobs were remained in the queue in created state, the retention policy would ensure it's removed. 

If you use the deferred options in `publish()`, the retention policy is evaluated at publish time and applies to 30 days after the deferral date or interval.  This will cause the job to stay around quite a bit longer if you use a date far into the future, but it's there if you need it.

**Comment by gc** [comment]
So, If I understand - in pg-boss we can publish jobs, but scheduling a job to run doesnt publish it, until its time to run it, so `await boss.schedule('analytics', `* * * * *`);` will publish a job every minute, so only if the job that it publishes didnt run within 30 days, it would be sweeped from the retention policy. I'm not sure yet how to publish something to run once at a specific date in pg-boss, but I'm assuming this also means that, it would only be sweeped because of the retention policy, 30 days AFTER the date its scheduled to run. If my understanding now is correct, thank you and lets close :)

**Comment by timgit** [comment]
:+1:
