### ISSUE TITLE
Multiple subscriptions

### ISSUE THREAD

**Issue by gc** [timgit/pg-boss#193]
```ts
const boss = new pgBoss({ ...postgresOptions, user: postgresOptions.username });
boss.on('error', (error) => console.error(error));
await boss.start();
await boss.schedule('analytics', `* * * * *`);
await boss.subscribe('analytics', async (job) => {
    console.log(`Subscription 1 is running: ${new Date().toString()}`);
    job.done();
});
await boss.subscribe('analytics', async (job) => {
    console.log(`Subscription 2 is running: ${new Date().toString()}`);
    job.done();
});
await boss.subscribe('analytics', async (job) => {
    console.log(`Subscription 3 is running: ${new Date().toString()}`);
    job.done();
});
```

Produces:
```
Subscription 2 is running: Sun Sep 06 2020 17:45:08 GMT+1000 (Australian Eastern Standard Time)
Subscription 3 is running: Sun Sep 06 2020 17:46:08 GMT+1000 (Australian Eastern Standard Time)
Subscription 2 is running: Sun Sep 06 2020 17:47:08 GMT+1000 (Australian Eastern Standard Time)
Subscription 3 is running: Sun Sep 06 2020 17:48:09 GMT+1000 (Australian Eastern Standard Time)
Subscription 3 is running: Sun Sep 06 2020 17:49:09 GMT+1000 (Australian Eastern Standard Time)
Subscription 1 is running: Sun Sep 06 2020 17:50:09 GMT+1000 (Australian Eastern Standard Time)
Subscription 1 is running: Sun Sep 06 2020 17:51:09 GMT+1000 (Australian Eastern Standard Time)
```

Whats going on here? I expected that all 3 subscriptions would run every minute? Instead just random ones indeterminately running?

Also secondary question, why is it not running at `50:00` `51:00` etc? and the interval went up by 1s midway? - I want it to run at the 0th second of every minute

Apologies if these are dumb questions I'm just investigating whether to use this library now and not sure how it works.

**Comment by timgit** [comment]
`schedule()` means "a job should be published according to this cron expression".  `subscribe()` means "fetch jobs from this queue on an interval".  Hopefully that clears things up.

**Comment by gc** [comment]
I still dont understand why i wouldnt get 3 logs running every minute, is it a race condition between the 3 subscribes on which one fetches it first? If so, shouldn't it maybe throw an error if you're trying to subscribe to the same event more than once?

**Comment by timgit** [comment]
I think the confusion may just be the semantics of what "publish" and "subscribe" mean in a task or job queue.  These terms are also used in pub/sub systems where listeners register to topics to respond to events in different ways.  While not a perfect analogy, consider the difference between AWS SQS and SNS.  pg-boss is like SQS, and what you're expecting I think is more like SNS.

**Comment by noamgat** [comment]
@timgit - Does onComplete follow the same semantics? I was just about to open an issue that if I register for onComplete twice, only one of the listeners gets called. Is this expected behavior?

**Comment by timgit** [comment]
Yes, onComplete() is also a job in a queue and follows "at least once" processing semantics
