### ISSUE TITLE
How to fetch job by job id

### ISSUE THREAD

**Issue by stovberpv** [timgit/pg-boss#194]
The `publish` method returns an `uuid` of the created job .
The `fetch` method allows to fetch jobs only by queue name.

Why there is no method for getting the job by it `uuid`, which we got after job publishing?

**Comment by timgit** [comment]
Would you say your use case is similar to [my reply in 188](https://github.com/timgit/pg-boss/issues/188#issuecomment-678005928)?

**Comment by stovberpv** [comment]
> Would you say your use case is similar to [my reply in 188](https://github.com/timgit/pg-boss/issues/188#issuecomment-678005928)?

I'm not sure ... In our case we build an API and business want to know does the job was published, what data is presents. This is some kind of a monitoring for a jobs, not for a entirely queue but for a concrete single job.
And i found it very weird, that the publish returns a `uuid`, we cant fetch a job by that `uuid`. Its like if we have an `insert` operator in `sql` but `select` is missing.

**Comment by timgit** [comment]
Jobs are temporary items in a queue.  Their lifetime is dependent on both retention policies and archive configuration.  You can use `onComplete()` to store important completion data and metrics, for example, but that job will be deleted from the database soon, so it's unreliable as an important entity with business value.  My intention with returning the job uuid was not to build a business entitty system, but rather a unique id that could be used if needed for troubleshooting.
