### ISSUE TITLE
Optimizing for speed

### ISSUE THREAD

**Issue by bhsiaoNFLX** [timgit/pg-boss#195]
Thanks again for the awesome library. I have two questions both related to the goal of churning through **jobs as quickly as possible**

1. Is there a way to configure `pg-boss` to grab from the queue _as soon as_ a job is done? i.e. a call to force "grab the next queue job?”

2. What subscribe / job polling options do you recommend to optimize for speed? Is there a known limit that you're comfortable sharing?

**Comment by timgit** [comment]
Speed can either be defined on a per-job basis or via distribution in aggregate using concurrency.  What kind of throughput are you wanting?  As a example, i have  [speed test](https://github.com/timgit/pg-boss/blob/master/test/speedTest.js) in the suite using batching in a single-instance configuration, but ultimately you could scale this out with as many instances that postgres can handle.

**Comment by bhsiaoNFLX** [comment]
thanks - your answer covers it. Also, sorry for the late response, posted this question on behalf of somebody else but forgot to followup.
