### ISSUE TITLE
Archiving Failed Jobs

### ISSUE THREAD

**Issue by jasonnz** [timgit/pg-boss#196]
PGBoss has two tables which store queued messages (job and archive).  Completed and Failed messages are moved to archive after a period of time.

Currently PGBoss is archiving Failed messages within a day.  This means that our IS Ops staff have less than 24 hours to deal to failed transactions before they are archived. Is it possible to configure that failed jobs are archived after a longer period?

**Comment by timgit** [comment]
The setting you're wanting is `archiveCompletedAfterSeconds`  The default archive interval is 12 hours.  I neglected to add this back to the configuration docs. It's only mentioned in the change log for 5.0.3.

**Comment by jasonnz** [comment]
Awesome thank you will try this :) Great app it works extremely well fo us.
