### ISSUE TITLE
unsubscribe could cancel pending worker

### ISSUE THREAD

**Issue by jcristovao** [timgit/pg-boss#198]
Hey!

First of all, thank you for the great library, we have been using it for some years now!

Now, I am considering including some 'slow' job queues on my tests (subscribe with `newJobCheckIntervalSeconds : 180`), but this means that even if I call `unsubscribe` on the `after` hook of the test, the test hangs until the latest Promise.delay finishes (which means, up to 3 minutes).

Would you consider making the code on `worker.js` have cancellation, something like this:

```
Promise.config({ cancellation: true });

class Worker {
  constructor (config) {
    this.config = config
    this.promise = null;
  }

  async start () {
    while (!this.stopped) {
      await this.config.fetch().then(this.config.onFetch).catch(this.config.onError)
      this.promise = Promise.delay(this.config.interval)
      await this.promise
    }
  }

  stop () {
    this.promise && this.promise.cancel();
    this.stopped = true
  }
}

```

(This was based on version 4.3.4, but it's easily adaptable to the latest version I guess)

I was conservative, I am not cancelling the fetch, only the wait between fetches to speed up the implicit clean-up.

What do you think?

**Comment by timgit** [comment]
I think it sounds like a good addition to the stop signalling.  Would you put this into a PR?

**Comment by jcristovao** [comment]
Sure! I may have a bit beginning of next week. Thank you
