### ISSUE TITLE
Understanding queue counts or possible stoppage of processing of jobs

### ISSUE THREAD

**Issue by amarchbanks** [timgit/pg-boss#202]
First of all, I’m absolutely loving this framework!

I’ve been using it within an app over the last few months to process millions of records. The last week I’ve been doing end to end tests to ensure everything is going well, but I’ve noticed something unusual. 

When the jobs are started I see the created count increase, and I see activity on the active count, and the all value also increasing. 

But at some point the queue statistics seem to stop changing, indicating that no jobs are being processed. Below is an output from the queue counts: 

Created: 9522483
Retry: 0
Active: 1
Expired: 0
Cancelled: 0
Failed: 0
All: 9571568

From my understanding “created” indicates pending jobs. If this is correct, then the job queue has stopped working. 

Can someone help clarify what the meaning of “created” means or help with diagnosing why the job queue has stopped processing?

This could just be my misunderstanding of the state values for jobs. 

Thanks in advance!

**Comment by amarchbanks** [comment]
I was able to overcome the stoppage of the queue by doing the following:

- upgrading to v5.0.8 (was on v4)
- adjusting the auto-vacuum settings on the table
- aggressively moving completed items out of the job table into the archive
- disabling supervisor and scheduling on my worker processes, and leaving it only enabled on the job producer worker

Let me know if anyone requires additional information for debugging.

**Comment by timgit** [comment]
Thanks for posting your resolution

**Comment by boredland** [comment]
>     * adjusting the auto-vacuum settings on the table
> Let me know if anyone requires additional information for debugging.

hey @amarchbanks what did you adjust the auto-vac to?

**Comment by amarchbanks** [comment]
@boredland sorry it was such a long time ago when I adjusted these settings, I can’t recall the exact change I made. What I can recall is that my particular setup was crawling to a halt with extremely slow query performance and I vaguely remember it would occur after several days after millions of inserts and updates (including archival). 

The following article explains some of the issues, but also some of settings available to adjust auto vacuum settings (apologies if you’re already aware of these settings): https://medium.com/@jramcloud1/mastering-autovacuum-and-vacuum-in-postgresql-the-complete-guide-for-dbas-fba18c2b2477

Are you also facing a similar situation?

**Comment by boredland** [comment]
Yes, I was trying to process several hundred million jobs and experienced significant slowness and also could sometimes see the vaccuum taking several minutes. One of your hints ("disabling supervisor and scheduling on my worker processes, and leaving it only enabled on the job producer worker"), helped to improve the speed to several hundred thousand jobs per minutes, but this still seems much slower to me, than necessary.

**Comment by timgit** [comment]
This issue was opened before v10, when partitioning was introduced.  The only way I've seen to handle this volume of jobs without a performance penalty is to partition the queues along with tuning the retention and deletion configs if necessary.

**Comment by boredland** [comment]
I tried to benchmark with

```
autovacuum_vacuum_scale_factor = 0.001,
autovacuum_analyze_scale_factor = 0.0005,
autovacuum_vacuum_cost_delay = 0,
autovacuum_vacuum_cost_limit = 10000
```

Applied to all the partitions of `jobs`. Which still is quite conservative. Auto-vacuum ran quite often and dead tuples were drastically reduced. I think there is some potential in those settings when aiming for high throughput, and especially when reducing a very high backlog. Will do more testing, tho, and probably report back when I load-tested this with millions of jobs.
