### ISSUE TITLE
Multi Threading

### ISSUE THREAD

**Issue by Israel001** [timgit/pg-boss#204]
Hi,

Please how does multi threading works in this library. 

I want to manually create multiple threads to test and handle Shopify api call limit. How do i do that?

**Comment by timgit** [comment]
pg-boss has concurrency features for parallelization (`teamConcurrency` is one example) within a single instance. But you can also achieve concurrency across instances as well. This isn't referred to as "threading" since node is a single-threaded event loop.

**Comment by Israel001** [comment]
I see, okay, thanks for the info.
