### ISSUE TITLE
Expiring a job that didnt start running?

### ISSUE THREAD

**Issue by noamgat** [timgit/pg-boss#205]
Hi,

We use pg-boss in a use case, where some of the jobs are fulfilled by external workers. We added an API call to our server that fetches a job in a queue, and the workers poll that API call.
We would like to time out jobs in a way, that if workers are down, jobs would time out.
However, the expiry options are only about jobs that started running - if the job crashed in the middle, it will expire and retry.
It does not cover the case where the process polling for the job crashes altogether.

Am I missing something? Is there a way to know when this happens?

**Comment by timgit** [comment]
Yes, when you call `fetch()` to pull a job from the queue, it's immediately set into active state.  pg-boss monitors for this and will expire the job if you don't call `complete()` or `fail()` within the expiration interval.

**Comment by noamgat** [comment]
Calling fetch() is done by the worker. What if the worker is down?

**Comment by timgit** [comment]
If the worker is down, the jobs will remain in the queue in created state.
