### ISSUE TITLE
are queues protected against dying processes?

### ISSUE THREAD

**Issue by andykais** [timgit/pg-boss#208]
Hi, I am new to this project and I have a question about error cases. I see that there are support for backpressure and retries, but I want to know what happens given this code:

```js
async function readme() {
  const PgBoss = require('pg-boss');
  const boss = new PgBoss('postgres://user:pass@host/database');

  await boss.start();

  const queue = 'some-queue';
  let jobId = await boss.publish(queue, { param1: 'foo' })

  console.log(`created job in queue ${queue}: ${jobId}`);

  await boss.subscribe(queue, someAsyncJobHandler);
}

async function someAsyncJobHandler(job) {
  process.exit(1)
}
```
if the function kills the process before the task is complete, is the task still recoverable? This is fairly important in production systems. Task workers are usually untrusted, and expected to crash occasionally, but the task queue should remain a source of truth that can be relied on. Essentially, I would expect tasks to have the following states:
`QUEUED`, `IN_PROGRESS`, `COMPLETE`, `FAILED`. In the case above, a task would remain in `IN_PROGRESS` until a task scheduler reschedules the task as `QUEUED` after a certain timeout.

**Comment by timgit** [comment]
In this case, the job will remain in active state until it expires.  The default expiration is 15 minutes.  If no retries are configured, it will be marked as expired and create a completion job with failed=true.  If you want retries, use `retryLimit` in `publish()`

**Comment by andykais** [comment]
👍 sweet. So long as the library isnt dependent on in process state, then this suits my needs. Closing
