### ISSUE TITLE
pgcrypto still needed?

### ISSUE THREAD

**Issue by DoReVo** [timgit/pg-boss#211]
Using the latest 5.08 version of pg-boss.

I successfully ran `boss.start()` without having pgcrypto installed as an extension. So do we still need the extension as mentioned in the documentation?

**Comment by timgit** [comment]
If this was the first time installing the schema, [this line](https://github.com/timgit/pg-boss/blob/da53e206dc15c502b05bf4a835811cfa6a206724/src/plans.js#L109) would fail if pgcrypto were not already installed in the target database.

**Comment by DoReVo** [comment]
Ah yes, somehow it didn't happened with my current database. But when i create a new database and try to start boss. It failed. So we still need it. Thanks.

**Comment by noinkling** [comment]
Note that as of Postgres 13, `gen_random_uuid()` is built-in: https://www.postgresql.org/docs/13/functions-uuid.html
