### ISSUE TITLE
Tasks that should publish while the process is offline

### ISSUE THREAD

**Issue by gc** [timgit/pg-boss#214]
I'm publishing a task with `publishAfter`, but it seems if the process is offline at that time, it acts really weirdly when my process comes back offline. My expectation is, any that should've been published while the process is offline will instantly publish/run when the process starts - is there something I need to do to get this result?

**Comment by gc** [comment]
This is probably just me not understanding something. What I found is, they're being published in serial 1 at a time, and if its hundreds of jobs, it can end up that they run much later than they should, rather than maybe running in parallel? Or is it a problem with the fact I should be using `await` or `job.done` differently? Apologies for my noobness with pgboss, I find it really really hard to understand all the options and stuff.

Code:

```ts
		await this.client.boss.subscribe('minionActivity', async job => {
			const data = job.data as ActivityTaskOptions;
			const taskName = taskNameFromType(data.type);
			const task = this.client.tasks.get(taskName);
			try {
				this.client.oneCommandAtATimeCache.add(data.userID);
				await task?.run(data);
			} finally {
				this.client.oneCommandAtATimeCache.delete(data.userID);
				if ('users' in data) {
					for (const user of (data as GroupMonsterActivityTaskOptions).users) {
						(this.client as OldSchoolBotClient).minionActivityCache.delete(user);
					}
				} else {
					(this.client as OldSchoolBotClient).minionActivityCache.delete(data.userID);
				}
				job.done();
			}
		});
```


somewhere else:

```ts
return client.boss.publishAfter(
		'minionActivity',
		newSubtask,
		{},
		new Date(finishDate)
	);
}
```

**Comment by timgit** [comment]
Yes, jobs will be processed one at a time unless you pass in concurrency options to subscribe()

**Comment by gc** [comment]
Ok so -

```ts
		await this.client.boss.subscribe(
			'minionActivity',
			{
				teamSize: 10,
				teamConcurrency: 10
			},
			async job => {
```

does this seem like an appropriate fix? I notice there's a "batchSize" option too,  but I really can't figure out what it does, the doc has almost same definition as `teamSize`, I also can't figure out what `team` means.

My understanding, now pgboss will FETCH up to 10  jobs per 2 seconds now, instead of 1 per 2 seconds, and now it can RUN up to 10 jobs (callbacks) at once. My uncertainty is all the other config options and whether i need those or if I'm using the wrong configs to achieve it, or if I'll need to change more config/options to fix it.

**Comment by timgit** [comment]
Yes, this will do what you described
