### ISSUE TITLE
Supervisor causing tests to hang

### ISSUE THREAD

**Issue by sdn90** [timgit/pg-boss#217]
I was unable to get my tests to cleanly teardown with `start` and `stop`.  Once I set `noSupervisor: true`, everything worked.

pg-boss: 5.0.8
pg: 8.5.1

**Comment by timgit** [comment]
pg-boss's test suite runs on every commit and is running fine.  What tests are you referring to?

**Comment by sdn90** [comment]
Hi, sorry for the short report. Thanks for your work on this library btw -- it's been working really well for me!  

In my codebase I'm using Jest for tests and my setup/teardown looks like this:

```javascript
beforeAll(() => pgBoss.start())
afterEach(() => pgBoss.deleteAllQueues())
afterAll(() => pgBoss.stop())
```

Without `noSupervisor: true`, my tests won't exit unless I send a SIGINT. I'm guessing its due to a connection or timer being active.

I had similar setup with the older API and never had an issue until the scheduling feature was introduced.

**Comment by timgit** [comment]
Thanks! I'm not sure what action I can take based on this.  These are all promise resolving, and I can confirm all of these function properly resolve, or else pg-boss's suite wouldn't work either.
