### ISSUE TITLE
Question: Multiple worker servers processing single queue name

### ISSUE THREAD

**Issue by Ollie1700** [timgit/pg-boss#218]
Hi guys 👋 Sorry for opening an issue for this but hopefully it's an easily answered question.

We have a system in place where business calculations are published to a single queue and we're at the point where sometimes backlog can be tens of thousands of jobs.

Business calculations take ~2 seconds so to avoid hours and days of backlog we're now looking into spinning up more worker instances based on number of jobs in the backlog.

So my question is, when spinning up more than one server that is subscribed to the same queue name, what important considerations are to be made in regards to pg-boss? Does pg-boss guarantee that a job will only be run once, or should we plan to account for this manually?

Apologies if this is a really simple one - I couldn't uncover too much detail regarding multiple worker systems in the documentation (hopefully I didn't just completely miss it!)

Thank you in advance!

**Comment by timgit** [comment]
Yes, you can create as many workers on the same queue as needed.

**Comment by Ollie1700** [comment]
Thank you for the confirmation!
