### ISSUE TITLE
Minor archive docs feedback

### ISSUE THREAD

**Issue by bhsiaoNFLX** [timgit/pg-boss#219]
If the `state` conditional is:
```
function archive (schema) {
  ...
  state < '${states.active}' AND keepUntil < now()
  ...
```

I.e. [configuration.md](https://github.com/timgit/pg-boss/blob/master/docs/configuration.md) should really be: 

> "...created **and retry** state before it's archived"

Am I right?

Also, `archiveCompletedAfterSeconds` is currently missing documentation even though there's a unit test for it. It should be documented.

If you agree, happy to create a PR :)

**Comment by bhsiaoNFLX** [comment]
Also, `archiveCompletedAfterSeconds` should be documented as well.

**Comment by timgit** [comment]
Yes. Please open a PR.  Thanks!

**Comment by bhsiaoNFLX** [comment]
https://github.com/timgit/pg-boss/pull/221/commits
