### ISSUE TITLE
production ready and dashboard

### ISSUE THREAD

**Issue by lludol** [timgit/pg-boss#224]
Hello,

I am normally using "Bull" on my projects for my clients. I had some problem on some featurea and I want to give a try on this pg-boss for a new client.

First of all, is it production ready?
I saw the coverage is 100% but is someone using this in production? (could be amazing to put in Readme some projets / companies using it)

Second of all, do you have a dashboard to manage and see an overview about your currents "jobs"?
For Bull I am using taskforce (https://github.com/OptimalBits/bull#uis), I was wondering if there is something similar for pg-boss or if it's on the roadmap?

Thank you.

**Comment by timgit** [comment]
Hey there. Infocyte has been using this in production for 5 years, and there are several others I've been in contact with, but I don't have their names available for publishing. 

There's not an included UI, which would require hosting a web server, as this package is the minimal runtime for background processing only. There is a monitoring event you can add a listener to on an instance to show summary queue sizes and their states if that helps.  You may be able to combine this data with something like Grafana, which would likely be a much more rewarding experience than something I would build. ;)

**Comment by lludol** [comment]
Thank you for your answer, I will check everything

**Comment by ryanmt** [comment]
This was a requirement to me when I was considering using pgboss for a SaaS product. I ended up subscribing to `monitor-states` and leveraging that as a source of information to scrape w/ prometheus and build up the rest of the operational monitoring/alerting I needed.  That required wrapping the job start in a server to respond to the metric scraping and to accommodate some liveness/readiness checks. All told, it wasn't very much lift.

**Comment by nahtnam** [comment]
In case anyone has come here from a google search, I've created a library for this. You can find details in this issue: https://github.com/timgit/pg-boss/issues/537#issuecomment-3310843364
