### ISSUE TITLE
pg-boss vs graphile-worker?

### ISSUE THREAD

**Issue by stephane-klein** [timgit/pg-boss#227]
Hi,

I have just seen **pg-boss** project from [Postgres Weekly](https://postgresweekly.com/) email.

I'm a [graphile / worker](https://github.com/graphile/worker) user and I wonder what are difference between **pg-boss** and [graphile-worker](https://github.com/graphile/worker).

This two projects achieve the same goals?

Same question on [graphile-worker issues](https://github.com/graphile/worker/issues/173)

Best regards,
Stéphane

**Comment by timgit** [comment]
Hey Stephane.  I haven't used graphile worker.  I probably would have if it been around 5 years ago when I needed it, however.  :)  At a high level, these projects look the same and will accomplish the same goals.  

Of course, I would argue how superior pg-boss is from an architectural perspective (:wink:) , but I imagine the graphile worker dudes would do the same for theirs.  The best suggestion I can offer is to try both and learn about these architectural differences. 

To provide a bit more info, one way that I often find myself describing pg-boss is similar to how AWS SQS works.  It's the client's responsibility to pull work from a queue, either on-demand or an interval. This is basically how pg-boss works with its subscribe and fetch apis.
