### ISSUE TITLE
PgBoss never exits

### ISSUE THREAD

**Issue by romandecker** [timgit/pg-boss#233]
Hey there!

thanks for this great library! I've found an issue that pg-boss never seems to free the pg-pool when scheduling is enabled. The following snippet never exits:

```js
const PgBoss = require('pg-boss');

(async function main() {
    boss = new PgBoss({
        host: 'localhost',
        port: 5432,
        database: 'postgres',
        user: 'postgres',
        retentionMinutes: 30,
        max: 1,
        // noScheduling: true  // <- uncomment this to make it work
    });

    console.log('start');
    await boss.start();

    console.log('stop');
    await boss.stop();
})();
```

If I pass `noScheduling: true`, it will properly exit, however, as soon as I do anything with pg-boss (like call `getQueueSize` for example, it will hang again, even with `noScheduling` set:

```js
const PgBoss = require('pg-boss');

(async function main() {
    boss = new PgBoss({
        host: 'localhost',
        port: 5432,
        database: 'postgres',
        user: 'postgres',
        retentionMinutes: 30,
        max: 1,
        noScheduling: true,
    });

    console.log('start');
    await boss.start();
    
    console.log('size', await boss.getQueueSize('crawl'));  // <- comment this to make it break again

    console.log('stop');
    await boss.stop();
})();
```

**Comment by ivank** [comment]
I would definitely echo this as a bug. In normal operations, waiting for 60 seconds might be fine, but when we run in in tests, 60 seconds to wait for the test is not something we'd like to do.
We are still on the last major version of pgboss (before the introduction of timekeep) because of this.
Maybe there is a way to start pgboss without timekeep in tests?

**Comment by zooplus-prs** [comment]
There is actually, we pass these options to PgBoss in our tests:

```
{
  noSupervisor: true,
  noScheduling: true
}
```

**Comment by romandecker** [comment]
There is actually, we pass these options to PgBoss in our tests:

```
{
  noSupervisor: true,
  noScheduling: true
}
```

**Comment by ivank** [comment]
Thanks @romandecker that pretty much solved our problems. Would love this to be documented a bit more prominently as it is the first thing you encounter as a problem when you write a test.
