### ISSUE TITLE
pg-boss ui

### ISSUE THREAD

**Issue by apiel** [timgit/pg-boss#234]
Would be great to have a web interface (I guess in a separate project) to be able to monitor pg-boss, see the queues, jobs and maybe to give the possibility to make some actions, like draining a queue. Something like RabbitMQ Management Interface (of course much more simple).

Maybe making an http middleware would be the best solution, so it could be integrated with existing API...

Thanks for this amazing project, it make our stack much more simple as we just need to rely on Postgres for all our data management.

**Comment by timgit** [comment]
> Was this closed because it was decided such a thing would be out of scope for this project?

Yes
