### ISSUE TITLE
Using ?ssl=true in connection string no longer works

### ISSUE THREAD

**Issue by stpe** [timgit/pg-boss#25]
In v0.5.0 using ?ssl=true in the database connection string worked fine, but not in v1.1.0.

Using a config object with `ssl` property set to true doesn't work either.

The issue seems to be in the Db constructor, not setting the `ssl` parameter or parsing it from the connection string:
https://github.com/timgit/pg-boss/blob/master/src/db.js#L17

**Comment by timgit** [comment]
You're right. This occurred when I switched over to pg's bundled connection pool which doesn't support connection string parsing like pg's client. 

I will add this back in 2.0 here pretty soon:
https://github.com/timgit/pg-boss/blob/89d0d7dcb99b8599893500277d3617ea27b39b50/src/db.js#L25

**Comment by timgit** [comment]
Released with 2.0.0
