### ISSUE TITLE
pgboss does not create tables if schema already exists.

### ISSUE THREAD

**Issue by amc6** [timgit/pg-boss#252]
It appears that pgboss will not create its tables if the schema (and just the schema) already exists. I think this can probably be fixed by changing the line to `CREATE SCHEMA ${schema} IF NOT EXISTS` but I haven't been able to test that to say for sure.

https://github.com/timgit/pg-boss/blob/5b0527637ad158f029aed617a6eee92f4f895a0c/src/plans.js#L118

**Comment by timgit** [comment]
This will be in an upcoming 6.1.0 release
