### ISSUE TITLE
Error - handler execution exceeded 0ms

### ISSUE THREAD

**Issue by hjr3** [timgit/pg-boss#255]
First, thank you for all the great features in the new 6.0.x version! We were so excited for them that we decided to upgrade early.

When we upgraded to 6.0.x, our database started getting crushed. I noticed the following error showing up:

```json
{
  "stack": "Error: handler execution exceeded 0ms\n    at expirationRace (/app/node_modules/pg-boss/src/manager.js:170:40)\n    at pMap.concurrency (/app/node_modules/pg-boss/src/manager.js:185:11)\n    at /app/node_modules/p-map/index.js:57:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "message": "handler execution exceeded 0ms"
}
```

I tracked it down to this code: https://github.com/timgit/pg-boss/blob/master/src/manager.js#L168-L171

It looks like there is some mismatch between what `plans.intervalToMs()` expects and what it actually receives.

Our `job.expirein` value is always `00:15:00` (or `900000` milliseconds). With some logging, it looks `plans.intervalToMs()` is getting this value in seconds (so `900`). Putting this in the repl:

```
> Object.keys(900).reduce((total, key) => total + INTERVAL_TO_MS_MAP[key] * interval[key], 0)
0
```

My suspicion is that this `expirationRace` is almost always throwing an error and, in effect, caused pg-boss workers to process jobs much faster than expected. This in turn caused the database performance issues I was seeing.

I tested my suspicion by deploying the following fix into production: https://github.com/timgit/pg-boss/compare/master...hjr3:interval?expand=1 and the performance issues and job failures immediately went away.

Sadly, I don't have a suggested fix. We are using postgres 11. When I fetch a job using the `fetchNextJob` SQL, I get:

```
id	name	data	expirein
b0f02890-c9fd-11eb-abf7-c5e024bdc319	receiveShopifyWebhook	{}	00:15:00
```

I am not following how `00:15:00` is supposed to map to an object that gets passed to `plans.intervalToMs()`.

I will also note that I think `plans.intervalToMs()` (or some code in `src/manager.js` should guard against a value of `0`. A `0ms` timeout is never what someone wants. Maybe defaulting back to the default of 15 minutes is the correct thing to do?

**Comment by timgit** [comment]
Thanks! I've published a beta release of a fix for this.  For some reason the pg driver didn't convert the interval properly, but I switched over to an int conversion in SQL to bypass this.

Use `npm i pg-boss@6.1.0-beta1` to see if it resolves your issue

**Comment by hjr3** [comment]
Apologies for the delay in responding. We have this running in production now and it is working great. Thank you.
