### ISSUE TITLE
Rows arnt automatically deleted  

### ISSUE THREAD

**Issue by Grigsuv** [timgit/pg-boss#258]
There are many this that I have seen old jobs in the `job` table that arent deleted after expires and keep until have passed, 
This is how config looks like 

` newJobCheckInterval: 10000,` 
    `expireCheckIntervalMinutes: 1,`
    `archiveCompletedAfterSeconds: 262800, // 73 Hours`
    `eleteAfterMinutes: 15,`
  `  maintenanceIntervalMinutes: 60 `
    
 Version: `^5.2.0` 
 
 There are no logs or other things that I can find, how can I find out the reason and fix this? Maybe update to lastest version will solve this ?

**Comment by timgit** [comment]
I recommend updating to the latest version

**Comment by Grigsuv** [comment]
@timgit are there any breaking changes? How can I find something like 'migration guide'?

**Comment by timgit** [comment]
see the [changelog](https://github.com/timgit/pg-boss/blob/master/CHANGELOG.md)

**Comment by Grigsuv** [comment]
@timgit ok thanks, I will try to update it, one last question,  can you provide some good examples of configuration? For example, should we use maintenance, what options can be helpful, etc...

**Comment by timgit** [comment]
No problem at all. I would recommend using the default options unless it produces an issue with your use cases.
