### ISSUE TITLE
Optionally support knex

### ISSUE THREAD

**Issue by cpsubrian** [timgit/pg-boss#26]
I'm working on integrating a queue into my feathers/knex app. Given that I already have a knex instance being passed around the app that is already a pooled pg connection, I'd love to be able to supply my own db 'adapter'. Basically all that would be needed is to support a 'db' option in the constructor and use that instead of constructing your own instance. I can mimic the API of your adapter easily enough.

Thoughts?

**Comment by cpsubrian** [comment]
Note: the main reason for this is my app manages setup/teardown of the db, as well as mocking it during test runs.

**Comment by timgit** [comment]
I don't have any objections to this.  It's basically just config parsing in the constructor and `executeSql()` and `close()` (recently added in the 2.0 branch).  I think it would be best to use this as an opportunity to move `migrate()` out of db and into contractor.

**Comment by timgit** [comment]
@cpsubrian I'm curious if you've tried monkey patching the returned pgboss instance by overwritng the boss.db property.

**Comment by cpsubrian** [comment]
Hey @timgit, unfortunately I'm not working on the same project at this point, so haven't/won't have a chance to try this. Thanks for looking back into it though :smile:
