### ISSUE TITLE
Thoughts around future dates and DST

### ISSUE THREAD

**Issue by ashconnell** [timgit/pg-boss#267]
As far as I can tell – when adding a job with a delayed date – pg-boss simply sends this date to postgres adhoc and postgres converts and stores it as UTC.

I might be missing something but I don't think this is fully protected against DST abolishment/rule-changes which can and do happen often. Take the following example:

1. Job created and delayed until `Nov 12, 8am Australia/Melbourne`
2. Postgres converts to UTC and stores: `Nov 11, 9pm UTC`
3. Australia abolishes DST before Nov 12

Now when the job runs, it will actually run at `Nov 12, 9am Australia/Melbourne`

This problem exists in any platform that needs to schedule future dates for local times, eg calendars, reminders, bookings, scheduling etc. These jobs are often used to send SMS/Emails or charge customers at **specific** local times.

pg-boss already has a `tz` option available for scheduled jobs via cron. This option isn't currently available for regular jobs but it could be. pg-boss could then (instead of using `pgboss.job.startafter=timestamptz`) use `pgboss.job.startafter=timestamp` and `pgboss.job.startaftertz=timezone`. The timezone would be optional and fallback to UTC for backward compatibility, and pg-boss would run queries as `pgboss.job.startafter AT TIME ZONE pgboss.job.startaftertz`

**Comment by jiayang26** [comment]
@ashconnell I believe this actually could be an important feature request for many use cases, wondering how can we escalate this?

**Comment by jiayang26** [comment]
cc @timgit

**Comment by ashconnell** [comment]
Yeah I’m not sure. It seems as though scheduling here is mostly only suited to dates in the short term
