### ISSUE TITLE
Add option for disabling prepared statements

### ISSUE THREAD

**Issue by sweber83** [timgit/pg-boss#27]
It would be nice to have an option to disable the use of prepared statements.
We are using pgbouncer with transaction pooling, which does not support prepared statements, so it would be nice If we could simply disable them.

**Comment by timgit** [comment]
What version are you referring to?  I think I removed the prepared statement in 1.0.0.  The latest release, 1.1.0, does not have it.

**Comment by sweber83** [comment]
Thanks for your help, we are still on 0.4.
Nice to know we can update soon :)
