### ISSUE TITLE
Error event is never executed

### ISSUE THREAD

**Issue by sundowndev** [timgit/pg-boss#273]
Hi, I've been implementing the lib successfully in dev, but error handling doesn't work as expected.

in my class Worker:

```js
this.instance = new PgBoss({
      host: host,
      port: port,
      database: database,
      user: user,
      password: password,
      ssl: ssl,
    });

    Sentry.init({
      dsn: sentryDsn,
    });

    this.instance.on('error', e => {
      console.error(e);
      Sentry.captureException(e);
    });
```

my queue:

```js
await this.instance.subscribe("test", () => {
     throw new Error('test')
    });
```

I created a test job that throws an Error, it fails as expected but the event error is never used. I've debugged it with my IDE and pg-boss never execute the function. Did I do something wrong ?

**Comment by timgit** [comment]
Errors in subscriptions are captured into the job itself. Error events on the primary instance are for "internal" operations such as maintenance.

**Comment by sundowndev** [comment]
> Errors in subscriptions are captured into the job itself. Error events on the primary instance are for "internal" operations such as maintenance.

Alright, so I have to catch job errors using a custom logic ?

**Comment by timgit** [comment]
Jobs that fail will store errors in the output jsonb storage in the job table.  If you need to react to job failures, you can use an `onComplete()` subscription and look for `failed: true` in the job data

**Comment by sneko** [comment]
Hi @timgit ,

I was trying to do the same to report errors to Sentry but I'm currently using `.work()` to set my handlers. Unfortunately `.on('monitor-states', ...)` does not work, neither `.onComplete(jobName, ...)` (the latter looks not compatible with `.work()` logic).

Did I miss something to catch error properly and report them? For now my workaround is to wrap each handler with:
```ts
export function handlerWrapper<ReqData>(handler: PgBoss.WorkHandler<ReqData>): PgBoss.WorkHandler<ReqData> {
  return async (job: PgBoss.Job<ReqData>) => {
    try {
      await handler(job);
    } catch (error) {
      // Wrapping to report error is required since there is no working way to watch job changes easily with `work()` method
      // Ref:
      Sentry.withScope(function (scope) {
        // Gather retry errors for the same event at the same place in Sentry
        scope.setFingerprint(['pgboss', job.id]);

        Sentry.captureException(error);
      });

      // Forward the error so pg-boss handle it as an error
      throw error;
    }
  };
}
```

**Comment by timgit** [comment]
What you're doing with try/catch is the recommended way of handling errors. If you also want to benefit from job retries and storing the error in the job, you would re-throw just like in your example.
