### ISSUE TITLE
monitor-states stops working after some time

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#275]
We have one single worker instance running and we are fetching the monitor states every 5 sec: `monitorStateIntervalSeconds: 5`.
In the `boss.on('monitor-states', ...` we store the result to view it in a frontend.

But every day when I wake up, the update stopped working during the night. I see no errors in the logs.

Have you seen that before? Or any hint how to debug this?

**Comment by timgit** [comment]
First, check the job table for the internal queue `__pgboss__monitor-states`.  If it's an error happening, you should see the state is not `failed` and the error should be in the `output` column.  You can also add logging to your event to try and correlate when the events stopped firing.

**Comment by phips28** [comment]
I am not finding any jobs that are failed:
```
select *
from pgboss.job
where name = '__pgboss__monitor-states'
  and state = 'failed'
```
Also checked `archive` table.
So I couldn't find any hint where it fails or stopped working.

I tried to throw an error in the listener, to see if it would be marked as failed in the DB, **but it doesn't**.

Listener:
```
this.boss.on('monitor-states', async (states) => {
	throw new Error('asdfadsf'); // does not result in failed __pgboss__monitor-states job
});
```

Is there an issue with that?

**Comment by timgit** [comment]
That's an event.  Node doesn't care if you throw in a listener to an EventEmitter

**Comment by phips28** [comment]
Ok true 🙈 

But then I dont know why the monitoring stopped working after some time. I am sending the timestamp as "Last updated" to my PM2 monitoring.
(ignore the formatting, thats PM2 UI)
![image](https://user-images.githubusercontent.com/3694800/135839194-00a03049-78bd-43bc-9ce6-6dbb72dacd8b.png)

The process 26 (last) has the last updated time = 1633343743 (=10/4/2021, 12:35:43 PM)
The current time of writing (on the server): 12:54:19 PM (~19min no update)

Config: `monitorStateIntervalSeconds: 5`
Max Jobs in job table: ~25k

Do you have any other idea what causes that?

**Comment by phips28** [comment]
Ah after sending this comment, I think I know 🙈 The monitoring state is a singleton, and only one worker processes this job. Therefore I see this (expected) behavior.
