### ISSUE TITLE
Is it possible to retry a job with delay and order ?

### ISSUE THREAD

**Issue by thomasthiebaud** [timgit/pg-boss#28]
Hi, 

I'm searching a way to retry a job with an exponential delay but while keeping the order. If I have the following queue ( with j1 and j2 some jobs)

```
// Queue
----------------------------------------
| j1 | j2 | .... <--- new jobs comming
----------------------------------------
```

I would like to execute `j1` and retry maximum X times with an exponential delay before trying to execute `j2`. (It must be blocking or locked until `j1` succeed or failed X times)

Is there an easy way to do it ?

**Comment by timgit** [comment]
`subscribe()` can't do this for you atm, but you can certainly roll this yourself via `fetch()`, `complete()`, and `onComplete()`.  `onComplete()` is still in the 2.0 beta release, so I'd really appreciate any feedback you can provide on that approach if you have a chance to give it a try.  I should be releasing 2.0 pretty soon.  I'm iterating on it to do my own testing and see if I like the API.

**Comment by thomasthiebaud** [comment]
Thanks for your answer, I will try to have a look today.

**Comment by thomasthiebaud** [comment]
I managed to get it work with `fetch()` and `complete()`. I did my own `onComplete()` function, but everything is ok. Thanks a lot.

If someone wants some code example I can provide it.

**Comment by timgit** [comment]
Awesome!  You sould post a link to a gist here if you're cool with that.  I can be that guy who wants your code example. 👍
