### ISSUE TITLE
worker: teamSize

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#30]
General question:

my settings:
```
"newJobCheckInterval": "1000",
"teamSize": 40
```

If I have a teamSize of 40 for a worker do every worker query the database every 1000ms?
Are there 40 queries per second in this config?

or is there 1 query to get 40 jobs and then spread it to the worker processes?

thx

**Comment by timgit** [comment]
It's currently the teamSize per interval queries.  I've been thinking about ways to optimize this recently for the `subscribe()` API.  My current thoughts are to use some local state in each instance to scale up to teamSize as a maximum concurrency as jobs start coming in, then scale it back down after a period of inactivity.  

Most of my time recently has been spent on optimizing fetch()` and `complete()` usage, but this does annoy me lol.

**Comment by phips28** [comment]
after digging deeper into the code I found it too :)

**My Idea for less DB queries:**
what is if you always run one `fetcher` for a worker instance.
This selects the `nextJob` with the `LIMIT %teamSize%` (e.g. LIMIT 40)
Then `forEach` the results and give the data to a worker which executes the job.
Its very straight forward.

In my example of `"teamSize": 40` I would have 40 queries/sec. And because they are almost started on the same time, they will use the whole poolSize (my settings 10) So I am adding 10 connections to the instance and database. 👎 
With the new approach we would only have 1 query/sec. And I only need 1 db connection in the pool, because no concurrency of queries 👍 

What do you think?

---

> scale up to teamSize as a maximum concurrency as jobs start coming in
I would say its not possible to scale just by adding "virtual workers" to the team, nodejs is event driven (single core) and has its limits, also in terms of memory.
We are using small EC2 instances and they are - as the name states - very small :D (but we use a lot of them.)
for now I try to find the right setting for a production ready pg-boss worker.
AWS Elastic Beanstalks is currently trimmed to scale up (add new instances) if CPU >30%

And scaling up server instances could just lead to a database crash -> adding connections -> adding more and more queries to the queue -> scaling up because everyhting is slow -> and so on ... sum it up ;)

**Comment by timgit** [comment]
I've also been thinking about whether batching via LIMIT would work given how SKIP LOCKED works.  If it works out with a large number of concurrent workers, I agree it would be ideal to reduce the query count and server load.  Have you tried this already?

**Comment by phips28** [comment]
It should work with SKIP LOCKED as it is now. I tested some queries on my pg with LIMIT 10. Looks good.

**Comment by phips28** [comment]
@timgit I created a new PR #32 for that, works really good and I am using it already in my production env with high volume events.

**Comment by timgit** [comment]
Thanks for the PR!  😁 I took your implementation and manually merged it into the 2.0 branch. `teamSize` will be retired in 2.0 and replaced with `batchSize` so it's a little more clear on what the option means.

**Comment by timgit** [comment]
Released with 2.0.0.  I left in `teamSize` after all for the `subscribe()` api
