### ISSUE TITLE
batchSize workers don't autocomplete jobs when the promise resolves successfully

### ISSUE THREAD

**Issue by tcoats** [timgit/pg-boss#312]
`batchSize` workers don't autocomplete jobs when the promise resolves successfully. Is this a conscious decision, or overlooked functionality? It would align with the normal worker if the async function returns successfully to indicate that all batched jobs are complete.

https://github.com/timgit/pg-boss/blob/8d34ab7426fb8c45e82df2b08cda7756ee63e4ea/src/manager.js#L217

**Comment by timgit** [comment]
This was intentional so I could more closely track completion times per job.  However, after you opened this, I realize the larger the batch, the less helpful it becomes to track individual completions, since all jobs in the batch share the same start time by design.

**Comment by codingedgar** [comment]
Thanks @tcoats, I was also a bit confused by how/when the job returned `[job]` and when `job`, and spend about 2h debugging why it did not complete (but did expire and fail) jobs when `batchSize` was specified.

I'm guessing for v7.0.2, if we have `batchSize` then we have to manually complete each job?
