### ISSUE TITLE
Backoff until maximum `retryDelay`?

### ISSUE THREAD

**Issue by adamhamlin** [timgit/pg-boss#340]
Curious if there's an idiomatic way to handle this kind of use case:
- I have a "retry" job that will run after a failure event is encountered (e.g., a remote server is down). It's important that this action take place _eventually_
- I want this job to use exponential backoff (`retryBackoff`), but at some point I don't want to keep doubling the delay. For example, maybe after I hit a 15 min delay, I want to just keep retrying every 15 minutes (instead of going to 30 min, 60, 120, etc)
- I'd like this job to just stick around until the failure is resolved (just use a very high value for `expireInHours`?)

I know that I could just implement the retry/backoff in my job handler, but is there a better way? Maybe using the `onComplete` callback to orchestrate? Or something else I'm overlooking?

Thanks for your time.

**Comment by timgit** [comment]
Yes, I would recommend using onComplete for this.

**Comment by adamhamlin** [comment]
Thanks
