### ISSUE TITLE
Should stop() when sending jobs from a lambda API? 

### ISSUE THREAD

**Issue by aecodalis** [timgit/pg-boss#344]
When sending jobs from a lambda API, is it recommended/required to `stop()` before ending of the function?

**Comment by timgit** [comment]
If you're using the minimal config of `noSupervisor=true` and `noScheduling=true`, and don't use `work()`, then calling `stop()` doesn't really have anything to stop.  It would be optional in that case

**Comment by ismailkarsli** [comment]
Hello, are these recommendations up-to-date? I will use Lambda/Cf Workers to send jobs to pg-boss and using `{ supervise: false, schedule: false }` is enough for this?

**Comment by timgit** [comment]
Yes
