### ISSUE TITLE
sendDebounced is dropping tasks

### ISSUE THREAD

**Issue by mladen107** [timgit/pg-boss#353]
Basically I have the same issue as described here: https://github.com/timgit/pg-boss/issues/81

I have multiple tasks that I want to execute but only once per minute. If I use sendDebounced multiple times, the first task is started immediately, the second task is scheduled after interval and all other tasks are dropped.

**Comment by timgit** [comment]
sendDebounced and sendThrottled behave the same, in the sense that at a high level, the goal is throttling a burst of incoming job.  There are good articles out there describing the differences, but I always prefer debouncing so I know that a job will always run after a burst of activity
