### ISSUE TITLE
Support for fetch all jobs from queue?

### ISSUE THREAD

**Issue by jianinz** [timgit/pg-boss#355]
When working with pg-boss, I noticed that one could configure the batch size, but what if I would like to fetch all jobs, it does not seem to support that in the latest stable version, is that right?

**Comment by timgit** [comment]
You can use fetch(), but you will need to specify the number of jobs

**Comment by jianinz** [comment]
Thanks for getting back to me @timgit. As time of writing, I specify a quite a large number as batch size, that kinda serves the purpose of what I initially want. But it will be great if it has API like fetchAll() : )
