### ISSUE TITLE
Ability to override query in Boss.countStatesCommand

### ISSUE THREAD

**Issue by craigdub** [timgit/pg-boss#356]
Would like the ability to override the query for 
[Boss.countStatesCommand](https://github.com/timgit/pg-boss/blob/8d34ab7426fb8c45e82df2b08cda7756ee63e4ea/src/boss.js#L40). The reason being is people may want to ignore testing/legacy jobs to be counted in these metrics by filtering within the query itself. Let me now what you think. Can help out with implementation here if you agree.

**Comment by timgit** [comment]
You can run the same query that pg-boss uses internally against the job table if you would like.  If you would like to continue using the event, perhaps you could use a naming convention to filter them out from the results.
