### ISSUE TITLE
A way for onComplete job to have retries

### ISSUE THREAD

**Issue by craigdub** [timgit/pg-boss#359]
I am trying to utilize onComplete feature but I am not finding a way to have retries on the __state__completed__ entries. 

I am concerned in the event of network errors or server restarts on deploy this will fail the completed jobs and then they will never get executed. 

Is there a way to do this?

**Comment by timgit** [comment]
There's no way to set retries currently for completion jobs.  :disappointed:

**Comment by craigdub** [comment]
Thanks for getting back! Curious, Is this intended by design or it just hasn't been implemented?

**Comment by timgit** [comment]
It's never been implemented

**Comment by timgit** [comment]
Completion jobs were replaced with dead letter queues in v10, which would support retries like any other queue.
