### ISSUE TITLE
 Calling boss.send() after boss.sendAfter(...DATE) causes it to also send after the DATE instead of immediately

### ISSUE THREAD

**Issue by pulpdood** [timgit/pg-boss#369]
Calling boss.send() immediately after boss.sendAfter(...DATE) causes it to also send after the DATE instead of immediately. I had to add a startAfter to the boss.send() options in order to get it to send immediately. It seems state is somehow leaking between the two sends? Sorry if this issue report isn't up to scratch, I'm not used to opening issues in projects.

E.g.

```
const job1 = await boss.sendAfter(QUEUE, data, CONFIG, futureDate);
...
const job2 = await boss.send(QUEUE, data2, CONFIG); // <- this will have its startAfter as futureDate instead of immediately
```

**Comment by timgit** [comment]
Thanks for reporting.  This should be resolved in 8.4.1
