### ISSUE TITLE
queue maintenance  with serverless workers

### ISSUE THREAD

**Issue by guy-borderless** [timgit/pg-boss#382]
If I offload job handling to serverless functions that take work via fetch(). How do I run queue maintenance periodically, preferably without creating a non-serverless queue worker? Is this scenario supported?

**Comment by timgit** [comment]
Running start() will automatically run maintenance unless you've opted out of this. If so, you may want to  create a dedicated function that runs on a cron and stays alive long enough to handle maintenance. You also won't have reliable use scheduling if you don't keep a supervisor process running

**Comment by guy-borderless** [comment]
Would you consider a PR that would allow a "serverless mode" to the queue (I'm currently using [qstash](https://console.upstash.com/qstash))? 
something like a function that can be called periodically to run maintenance, set schedules, and ping the URLs of the job handlers according to the number of open jobs?

**Comment by timgit** [comment]
Yes!  Thanks

**Comment by timgit** [comment]
This is supported now in v10

**Comment by boredland** [comment]
hi there! I think I don't understand how this could work in a serverless environment. what part of the docs would I need to look at?

**Comment by timgit** [comment]
It's the maintain() function.  This made it into the release notes, but not the docs.  Apologies for missing that.
