### ISSUE TITLE
Can an already started job be aware about a cancel request about it?

### ISSUE THREAD

**Issue by iccicci** [timgit/pg-boss#384]
Hi all, this is more a clarification request than an issue.

I'm wondering about the case when a job is started and it receives a _cancel_ request while it is running; has the job some way to know about that?

Thank you in advance.

**Comment by timgit** [comment]
pg-boss will change the state of the job to cancelled if it's not completed or failed, but it will not interact with a worker awaiting a promise.

**Comment by timgit** [comment]
Yes

**Comment by iccicci** [comment]
Thank you @timgit
