### ISSUE TITLE
onComplete Typoes

### ISSUE THREAD

**Issue by ctaity-treinta** [timgit/pg-boss#386]
Hi what is the type of the job in the onComplete handler function?

The type of job variable in the following example?

```
boss.onComplete(jobName, job => {
    assert.strictEqual(jobId, job.data.request.id)
    assert.strictEqual(job.data.request.data.token, requestPayload.token)
    assert.strictEqual(job.data.response.message, responsePayload.message)
    assert.strictEqual(job.data.response.code, responsePayload.code)

    finished() // test suite completion callback
})
```
Thanks.

**Comment by timgit** [comment]
The docs has an example job payload, which is customized for onComplete:
https://github.com/timgit/pg-boss/tree/master/docs#oncompletename--options-handler
