### ISSUE TITLE
The library does not support PostgreSQL 11, just 13+

### ISSUE THREAD

**Issue by dima-guzman** [timgit/pg-boss#413]
In our project we use the library of version 9.0.3 with PostgreSQL 11 and it does not work, because the function
gen_random_uuid() was only introduced in PostgreSQL 13.
Please use uuid_generate_v4() from uuid-ossp or update the minimum version.
In Azure the **maximum** version is 11 so can the issue be fixed for this version?

**Comment by timgit** [comment]
The installation instructions in the docs mention you need to manually install pgcrypto
