### ISSUE TITLE
High Database CPU when processing backlog

### ISSUE THREAD

**Issue by fenos** [timgit/pg-boss#418]
Hello, firstly let me take a second to give my appreciation to pg-boss, great library!

We are noticing an increase in CPU consumption on the Database when a backlog of jobs is building up.
The chart looks like this:

<img width="513" alt="image" src="https://github.com/timgit/pg-boss/assets/4754064/b610c33b-a9e6-4383-835d-338a091d160b">

From the investigation, it seems that the workers pulling the jobs are putting too much strain on the Database CPU when it can't keep up.

You can see from the graph below that the CPU was quite stable, however during the raise a producer started queuing many more messages. The enqueue operation doesn't seem correlated to CPU usage. 
Subsequetially the Drop in CPU was caused by canceling all the jobs via a SQL query

<img width="2426" alt="image" src="https://github.com/timgit/pg-boss/assets/4754064/85e200d5-f03c-412f-87a6-cef854535a9b">

The workers are set up as follows:

```ts
 new PgBoss({
      connectionString: url,
      max: 4,
      application_name: 'pgboss',
      deleteAfterDays: 7,
      archiveCompletedAfterSeconds: 14_400,
      retentionDays: 7,
      retryBackoff: true,
      retryLimit: 20,
      expireInHours: 48,
      monitorStateIntervalSeconds: 30,
     newJobCheckInterval: 700,
    })
```

on the job handler, we use async / await to build up back pressure. Just to clarify the handler doesn't issue any SQL statement to this database, so the load is purely from pg-boss

We are currently running 1 worker in 4 separate containers, so each container should pull 1 message at a time.

I'm unsure why pg-boss would incrementally use more Database CPU even if the concurrency is set to 1 and the next message shouldn't be fetched until the previous one completes.

Currently, we are ok with processing these messages slower than they get produced, however, we can't justify the CPU increase.

Do you know what might cause the CPU to spike up internally in pg-boss?

**Comment by timgit** [comment]
How many records were created in the job table when the util was high?

**Comment by fenos** [comment]
@timgit After further investigation it seems that the issue is caused by the sorting on the `nextJob`
https://github.com/timgit/pg-boss/blob/master/src/plans.js#L379

Since there is no compound index on these columns when the table gets big, Postgres would start doing a disk merge sorting, causing high CPU usage as the table gets bigger.

I'm wondering if adding an index on the sorted columns could help speeding up things and reduce the load on Postgres when sorting

**Comment by fenos** [comment]
@timgit we have upgraded the RDS instance to a db.t4g.xlarge and unfortunately, this issue is still happening, is there anything we can do maybe as mentioned above, adding an index to the sort columns to reduce the disk sorting operation?

**Comment by timgit** [comment]
I have tried several times to build the best index for job fetching, but apparently this work will be ongoing. 😄 If you're up for it, can you experiment with your job table to find out what index best helps your use case?

**Comment by DonKoko** [comment]
hey @fenos . Did you manage to find a solution for this? We are kinda stuck in this situation and our DB CPU user keeps on increasing.

**Comment by fenos** [comment]
Yes, the "solution" is to have the least active jobs as possible as well as setting:

- `teamSize: 200` (this option is very very important as it will reduce the amount of queries issued to the database)
- `teamConcurrency: depends on your resource` this will allow to process more jobs concurrently

**Comment by sledorze** [comment]
@fenos had you tried to add an index ? if so, what was it and the result ?

**Comment by timgit** [comment]
In v9, all jobs, including internal maintenance jobs, share the same storage. In our experience, once we have > 1mil jobs, the performance of SKIP LOCKED starts to suffer.  v10 introduced job storage partitioning, which should isolate perf issues to only the queue in question.  This strategy is still being evaluated and not yet in production, but you are welcome to try out a beta release if you would like an early preview.

**Comment by timgit** [comment]
Please re-open if this continues to happen in v10
