### ISSUE TITLE
feature-request: It should be possible to predict a job key or id. 

### ISSUE THREAD

**Issue by nuelsoft** [timgit/pg-boss#419]
There are cases where an actor would want to replace an already scheduled job. The current solution doesn't allow for this or any kind of job filtering by data jsonb object. 

An example use-case

```ts

function schedulePendingActionNotificaion(userId: string) {
  const queue = 'pending-actions-notifcation'
  const key = `pending-action::${userId}`
  boss.cancel({name: queue, key})
  boss.send(queue, {userId}, { key })
}
```

This doesn't have to replace the existing `id`, It should only another possible reference that can be predicted uniquely

**Comment by timgit** [comment]
This would be a good option to send(). You can use insert([jobs]) for now, however.

**Comment by jorinvo** [comment]
Thanks @timgit! `insert()` does what we need. And thank you for the work on this lib :)

**Comment by nuelsoft** [comment]
Hello @timgit, thank you for the pointer. I was more worried by this https://github.com/timgit/pg-boss/blob/64df1e471fdd44469702467ff09420c7396ba685/src/plans.js#L138 

It would be nice to maybe drop the type from uuid to a more flexible string. 

Thanks again.

**Comment by timgit** [comment]
`send()` now supports an `{ id }` option in v10
