### ISSUE TITLE
Use pg-boss with postgres.js

### ISSUE THREAD

**Issue by StarpTech** [timgit/pg-boss#420]
Hello, it would be great if pg-boss could support [porsager/postgres](https://github.com/porsager/postgres) because it is very popular. I tried to make it work but I gave up after an hour. Any help is appreciated.

**Comment by timgit** [comment]
You can pass in porsager's project via the `db` option in the constructor if you want.  In terms of popularity, one of these is not like the other:
![image](https://github.com/timgit/pg-boss/assets/656974/86ff36d5-7851-4e69-b5e6-ee2da898c335)

**Comment by timgit** [comment]
How does the dependency on pg affect your usage?

**Comment by StarpTech** [comment]
Not directly, but if I could only use postgres.js I'd have a single way to configure TLS and pool management. Postgres drivers are complex. One thing less to worry about.

**Comment by StepanMynarik** [comment]
@StarpTech @timgit 
Same situation here.
Also **porsager** authors _claim_ their driver has top performance by far.

**Comment by ohueter** [comment]
I know this is an old issue, but here is my solution to using `postgres` with `pg-boss`:

```ts
import postgres, { type Sql } from 'postgres'
import type { IDatabase } from 'pg-boss/dist/types'

export const postgresAdapter: (sql: Sql) => IDatabase = (sql: Sql) => ({
  executeSql: async (query: string, values?: any[]) => {
    // Reserving a connection is required because pg-boss starts transactions
    const reserved = await sql.reserve()

    // pg-boss inserts jobs with a query containing `json_to_recordset($1::json)`
    // with value being a stringified JSON object, which causes an error with the `postgres` package.
    const parsedValues = values?.map((v) => {
      if (typeof v !== 'string') {
        return v
      }

      try {
        return JSON.parse(v)
      } catch {
        return v
      }
    })

    // Calling unsafe() this way is safe when the query
    // contains placeholders ($1, $2, ...) for the values
    const rows = await reserved.unsafe(query, parsedValues)

    reserved.release()
    return { rows }
  },
})

const sql = postgres(/** postgres url, options, etc */)

const boss = new PgBoss({
  db: postgresAdapter(sql),
})
```

Maybe this will help someone in the future.

@timgit It would be great if `pg` was declared as peer dependency because then it could be omitted as direct dependency of the project. Currently, just leaving it out leads to quite verbose logging from `pg`:

```
Package pg can't be external
The request pg matches serverExternalPackages (or the default list).
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install it into the project directory by running npm install pg from the project directory.
```

**Comment by timgit** [comment]
I'm leaning towards removing pg as dep, yes.  I like how drizzle handles this, so I'd likely follow their pattern and support pg + postgres

**Comment by bensaufley** [comment]
FWIW [9 million weekly downloads](https://npmx.dev/compare?packages=postgres,pg) is still a fraction of `pg`'s, but it's sure more than nothing these days.

<img width="684" height="439" alt="Image" src="https://github.com/user-attachments/assets/332eccfa-77f8-4779-8a5d-0c4da2b8691f" />
