### ISSUE TITLE
Stopping pg-boss gracefully does not wait until stop timeouts

### ISSUE THREAD

**Issue by StarpTech** [timgit/pg-boss#421]
Hi, it looks like pg-boss does not respect `graceful` nor `timeout` property. I have a simple worker that needs at least 5 seconds to finish. On `SIGTERM` I clean up all my server resources but `boss.stop` does not block until the max timeout of 30s is over.

```ts
await fastify.pgboss.send(queue, { some: 'data' });

await fastify.pgboss.work(queue, async function someAsyncJobHandler(job) {
  console.log(`job ${job.id} received with data:`);

  // promise wait
  await new Promise((resolve) => setTimeout(resolve, 5000));

  console.log(job);
});

 const stopOptions: PgBoss.StopOptions = {
     timeout: 30_000,
     graceful: true,
	 destroy: false
};
await boss.stop(stopOptions);
```

**Comment by StarpTech** [comment]
Must be a regression. Works in https://github.com/timgit/pg-boss/releases/tag/8.3.0

**Comment by StarpTech** [comment]
Nevermind, I can't reproduce it anymore after cleaning up and rebuilding everything from scratch :confused:

**Comment by StarpTech** [comment]
My fault. I still had a timeout in the shutdown phase. The bug is still valid.

**Comment by StarpTech** [comment]
I was able to workaround this by 

```ts
await boss.stop(stopOptions);

await new Promise((resolve) => {
  boss.once('stopped', () => resolve(null));
});

fastify.log.info('PgBoss shutdown complete');
```

**Comment by timgit** [comment]
PRs are always welcome. I think it should be opt-in via as a new option on stop().  Thanks!

**Comment by StarpTech** [comment]
What's the reason for passing it onto the next cycle [here](https://github.com/timgit/pg-boss/blob/64df1e471fdd44469702467ff09420c7396ba685/src/index.js#L154)?

**Comment by StarpTech** [comment]
@timgit friendly ping.

**Comment by timgit** [comment]
Hold off on the PR.  v10 will include this

**Comment by StarpTech** [comment]
@timgit thank you. Any eta?

**Comment by timgit** [comment]
Interested in the beta?

**Comment by StarpTech** [comment]
Sure
