### ISSUE TITLE
Is pg-boss actively maintained?

### ISSUE THREAD

**Issue by StarpTech** [timgit/pg-boss#424]
Hey, I'm not a fan of opening such issues but pg-boss becomes serious to us. We would like to use it in our production projects. I have opened a couple of issues and we would love to contribute back but it needs active maintenance. I saw the last release was months ago and only a very few issues got feedback from you. People are very interested in your work, and running productions workloads and it would be very sad if nobody maintains it. @timgit please clarify the situation so we can make a decision on it. Small motivation https://twitter.com/dustindeus/status/1695891695966003564 :heart:

**Comment by timgit** [comment]
Months ago, as in last month?  Are you not entertained? ;)  

![image](https://github.com/timgit/pg-boss/assets/656974/d5fa9c32-b5a1-494f-86eb-de6bf968f323)

Thanks for the feedback, and I hope you're finding value in it.

**Comment by StarpTech** [comment]
:popcorn: Great to hear!
