### ISSUE TITLE
Deleting/clearing queue

### ISSUE THREAD

**Issue by roytz** [timgit/pg-boss#43]
Is there a way (beside connecting to PG and doing it manually) to delete all jobs using pg-boss api?

**Comment by timgit** [comment]
No. I do this manually during testing.

**Comment by chrisjensen** [comment]
Do you still do this? I'm having trouble finding an example in the tests.

**Comment by timgit** [comment]
There's no api for it atm

**Comment by chrisjensen** [comment]
Oh, when you said manually, I thought you meant there was a `DROP ALL` or `TRUNCATE` statement somewhere in the tests.

**Comment by timgit** [comment]
Yes, `/test/testHelper.js` has a couple scripts to delete things for some tests, but it's not surfaced in the pg-boss module.
