### ISSUE TITLE
Document onComplete option

### ISSUE THREAD

**Issue by unzico** [timgit/pg-boss#432]
Hi there,

thank your very much for developing this valuable project.

Unfortunately, I just spent a few hours trying to figure out why the `onComplete` feature (documented [here](https://github.com/timgit/pg-boss/blob/master/docs/readme.md#oncompletename--options-handler)) didn't work. Turns out, one has to enable it when instantiating `pg-boss`.

**Example:**
```typescript
import PgBoss from "pg-boss";

const pgBoss = new PgBoss({
  // option must be enabled for pgBoss.onComplete to work
  onComplete: true,
});

// now I can use it like so
pgBoss.onComplete("*", (job) => { ... })
```

However, this requirement is neither documented in the ['instantiate pg-boss with options' section](https://github.com/timgit/pg-boss/blob/master/docs/readme.md#newoptions) nor the ['onComplete method' section](https://github.com/timgit/pg-boss/blob/master/docs/readme.md#oncompletename--options-handler).

**Note**: I just noticed there's a small documentation about it in the section about the [`send` method](https://github.com/timgit/pg-boss/blob/master/docs/readme.md#newoptions).

I wish it would be obvious that one has to enable this option globally to make use of this feature :).

**Comment by timgit** [comment]
I don't have a release date in mind yet, but v10 removes this option completed, so one way or another, the documentation issue will be resolved. :)
