### ISSUE TITLE
Allow the job handler of subscribe() to process all fetched jobs at once

### ISSUE THREAD

**Issue by haoliangyu** [timgit/pg-boss#45]
Currently the job handler function of `subscribe()` is called for each fetched job. It would be sweet if there is an option to allow the handler to receive an array of all fetched jobs. In my use case, doing a batch processing with all fetched jobs could help to significantly reduce system workload.

``` javascript
boss
  .subscribe(
    'my-queue', 
    { batchSize: 50 }, 
    (jobs) => batchProcess(jobs)
  );
```

This is the expected usage. Though it could be achieved by periodically calling `fetch()`, a native support is better (and implementing it looks simple after reading the source code).

**Comment by timgit** [comment]
I agree.  Currently, the docs use `teamSize` for the behavior to assume a single job per invocation, but since internally it currently supports both `teamSize` and `batchSize`, it would be easy to just split these options apart and have them behave differently, such as in your your example.

**Comment by haoliangyu** [comment]
If that's the decision, I would be happy to write a PR for it.

**Comment by timgit** [comment]
Sounds great!  Thanks
