### ISSUE TITLE
Typo in validation for Postgres names

### ISSUE THREAD

**Issue by eloff** [timgit/pg-boss#457]
`assert(!/^d/.test(name), 'Name cannot start with a number')`

You mean `\d`. I had a name that started with a d, and the error took me a while to figure out.

https://github.com/timgit/pg-boss/blob/10.0.0-beta2/src/attorney.js#L182

**Comment by EvertEt** [comment]
A fix for this has been merged in https://github.com/timgit/pg-boss/pull/455 but not published yet

**Comment by timgit** [comment]
This has been published in the latest beta tag

**Comment by eloff** [comment]
> This has been published in the latest beta tag

Oh, I see. There's only up to beta2 in tags in this repo, but beta5 is the latest on npm. That threw me.
