### ISSUE TITLE
Tests failing in CI workflow

### ISSUE THREAD

**Issue by rustworthy** [timgit/pg-boss#462]
Hey @timgit ! Thank you for this piece of software. I am really enjoying it.

I was trying to set up the environment for local development (wanted to suggest updating some deps and retiring a `delay` lib), but  failed to run the tests successfully. The  issues I got are reproduced on the CI: one yelling about [too many clients](https://github.com/rustworthy/pg-boss/actions/runs/10074833228/job/27851825936) and the other about a violation for [pg_extension_name_index](https://github.com/rustworthy/pg-boss/actions/runs/10072144193/job/27843533816). 

I see the only extension that is being created is `pgcrypto` and I wonder if this error can be due to some race? After using [try](https://github.com/rustworthy/pg-boss/blob/16bdfcc45d10b317680b0932e232994bba82ae2a/test/testHelper.js#L66-L74) logic, the error has gone, but I hate this solution and I am not sure this is even a solution.

JFYI, for local development, I am setting things up this way:
```sh
docker run --name pgboss -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 -d postgres

# after the test run
docker stop pgboss && docker rm pgboss

# and then  spin up a new container for another test run (just for sanity)
```

Maybe you've encountered these issues previously?

**Comment by timgit** [comment]
Thanks!  I'm devoting all of my current efforts towards v10, so please try using that branch since it should be released in a few weeks.
