### ISSUE TITLE
Publish an array of jobs

### ISSUE THREAD

**Issue by haoliangyu** [timgit/pg-boss#47]
Now the `publish()` function process a job at a time and if there are multiple jobs to publish, we run the `publish()` function in a loop. Given that inserting multiple rows in a query is more efficient, it seems to be a good idea to extend the function to accept an array of requests.

In our use case, our system receives data update notifications and publishes several different jobs for each notification. We are considering ways to send fewer queries in order to reduce I/O.

If the publication fails, all jobs fail. But I think the user can use the function at his own risk.

**Comment by timgit** [comment]
I agree on all points.  I'll add this to the 3.0 list.  It's something that's been bugging me more recently as my job volumes have increased.  

The assumption I'll make at this point is opting into this API implies one should supply uuids to the jobs along with the data payload.  The promise would then simply resolve `true` for a successful publish, or reject if any of the jobs were not saved.

**Comment by bradleyayers** [comment]
This would be quite handy for me too. I want to implement a daily aggregated data reports, by having a single event that recurs daily, and its handler creates N jobs (one per report). The reports are unique to each customer of my product.

**Comment by robgraeber** [comment]
+1 I've been manually batching the jobs, e.g. passing big arrays in the data field.
