### ISSUE TITLE
Runs the job but gives abort error on Bun

### ISSUE THREAD

**Issue by PietroDSK** [timgit/pg-boss#472]
So, I'm using pg-boss with bunjs.
I'ts all running OK, except that error
```
18 |       .catch(resolve)
19 |   })
20 | 
21 |   promise.abort = () => {
22 |     if (!ac.signal.aborted) {
23 |       ac.abort()
           ^
error: The operation was aborted
 code: "ABORT_ERR"

      at new AbortError (node:timers/promises:172:27)
      at node:timers/promises:46:35
      at /Users/pietro/Documents/Bemobile/be-synced/node_modules/pg-boss/src/tools.js:23:7
      at /Users/pietro/Documents/Bemobile/be-synced/node_modules/pg-boss/src/manager.js:29:5
```
Every time that a job runs, this error is returned.
The job is completed normally and the server keeps running without problems, someone already experienced this?

**Comment by timgit** [comment]
Is it related to [this issue](https://github.com/oven-sh/bun/issues/9429)?

**Comment by PietroDSK** [comment]
yeah, exactly.
Upgrading the version of bun solved the problem.
Thanks a lot.
