### ISSUE TITLE
Use PostgreSQL client directly

### ISSUE THREAD

**Issue by adriaanvanrossum** [timgit/pg-boss#48]
I'm using *pg-boss* as a part of an express app. In that express app I use _sequelize_ for interacting with the database. When I run *pg-boss* it does setup a new connection to my database. Can I setup  *pg-boss* in such a way it uses the same database connection as _sequelize_ does?

**Comment by timgit** [comment]
Adriaan,  I currently have this a on my 3.0 list but I think it's achievable before then with some small constructor changes.

**Comment by adriaanvanrossum** [comment]
That would be awesome. Hopefully the sequelize team will do the same (https://github.com/sequelize/sequelize/issues/8967).

**Comment by terehov** [comment]
We are working on a postgres-centric node framework and were planning to integrate PGBoss. Since we have a pool manager across multiple nodes, we would need this functionality as well. Thumbs up!

**Comment by timgit** [comment]
The above commit is included in 2.4.0.  It's sort of "underdocumented" atm.  The response pg-boss expects is that of the pg module.  `rows` array, `rowCount` property when an update was run, etc.

**Comment by adriaanvanrossum** [comment]
Thanks, it works! How I did it (with [sequelize](https://github.com/sequelize/sequelize/issues/8967)), it maybe help others

```js
// initializers/pg-boss.js
const db = require('../models'); // Your sequelize db export
const PgBoss = require('pg-boss');

const start = new Promise((resolve, reject) => {
  const getConnection = db.sequelize.connectionManager.getConnection();

  getConnection.then(connection => {
    // Add `close` and `executeSql` functions for PgBoss to function
    const PgBossDB = Object.assign(connection, {
      close: connection.end,
      executeSql: connection.query
    });

    const boss = new PgBoss({ db: PgBossDB });
    boss.on('error', console.error);
    boss.start().then(resolve).catch(reject);
  }, reject);
});

module.exports = start.then(pgBoss => pgBoss).catch(console.error);
```

And run it in another file

```js
// runners/jobs.js
const pgBoss = require('../initializers/pg-boss');
const addJob = job => {
  // Something with the job
  job.done();
};

pgBoss.then(jobs => {
  jobs.subscribe('add-job', addJob).catch(error => {
    console.error('[JOB] Subscribe:', error);
  });
}).catch('[PG BOSS]', console.error);

```

**Comment by timgit** [comment]
Great!  Btw, `close()` is not required.
