### ISSUE TITLE
pollingIntervalSeconds question

### ISSUE THREAD

**Issue by afedotov-align** [timgit/pg-boss#487]
Hi @timgit ,

Could you please explain the logic of pollingIntervalSeconds parameter?

We have a scheduled job, and pollingIntervalSeconds set to 10 (seconds), and our job never actually got executed (there should be log), but in the database it says that it's completed.
Then when we set pollingIntervalSeconds to 0.5 seconds - it's executed.
How does it work with pollingIntervalSeconds and why might this happen?

Thanks, Artem.

**Comment by timgit** [comment]
Can you post your code?
