### ISSUE TITLE
Changing schema name leads to an error

### ISSUE THREAD

**Issue by terehov** [timgit/pg-boss#50]
Hi Tim, 

I was trying to change the schema name from `pgboss` to `_queue` the way you mention in the documentation:

```
{
    database: ...,
    host: ...,
    user: ...,
    password: ...,
    poolSize: 1,
    archiveCompletedJobsEvery: '2 days',
    schema: '_queue'
  }
```

This creates the DB as expected. There is a `_queue` schema with two tables in it `job` and `version`. On the second run, however, I get an error. This does not happen when I either leave `schema` out, or set it to `pgboss`. 

Error:
```
{ error: operator does not exist: character varying < _queue.job_state
    at Connection.parseE (.../node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (./node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'error',
  length: 224,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',
  position: '121',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '728',
  routine: 'op_error' }
```

Do you maybe have an idea? 
thanks!

**Comment by timgit** [comment]
🤔 perhaps it’s the leading underscore?  Have you tried other names?

**Comment by terehov** [comment]
Yes

**Comment by timgit** [comment]
What do you mean by second run?  Just disconnecting and reconnecting?  I wrote another test for this tonight but couldn't reproduce it.

**Comment by terehov** [comment]
Sorry, I should have clarified it a bit better before. 
It happens when I restart my node process. So the first run seems to be okay, it creates this schema wilt the two tables, but as soon as I restart the server this error appears.

**Comment by timgit** [comment]
Were you able to find out the cause?  Besides the tests, I can't reproduce this with your settings in my app.
