### ISSUE TITLE
no more fetchAll?

### ISSUE THREAD

**Issue by boehm-e** [timgit/pg-boss#512]
I try to fetch all jobs from a queue using this code:
```
const fetchedJobs = await queue.fetch("my-queue", { includeMetadata: true, batchSize: 20 });
```

but i only get `active` jobs,
I would like to have all jobs of the queue including the `created` and `completed` ones.
I see in other issues that there was a function fetchAll, but it looks like it has been removed.
Also i found nothing about that [in the documentation](https://timgit.github.io/pg-boss/#/./api/jobs?id=fetchname-options).

Is there a way to retrieve all jobs from a queue?

**Comment by timgit** [comment]
There's never been a fetchAll(), but you can use SQL for what you need for now
