### ISSUE TITLE
Handling non-retryable errors

### ISSUE THREAD

**Issue by eric-gonzalez-tfs** [timgit/pg-boss#516]
Hello all,

Thank you for the hard work on `pg-boss`! We find that the library is well thought-out and is constantly improving.

I have some jobs set up using `pg-boss`'s retry mechanism. However, there are scenarios where the current job may fail, but I do not want to retry due to a fatal error. I've tried adding a call to `boss.fail(name, id)`, however, when the job bounces out of the handler, it appears to set it back to a "retry" state.

What is the best approach to telling `pg-boss` that a failure happened, but we do not wish to try again?

Thanks!

**Comment by timgit** [comment]
To opt out of the configured retry, the only option I can think of is to delete it

**Comment by rrindels** [comment]
We do something similar with deleting the current job but creating a new
job with our original payload +additional  error payload in another queue
which are handled with different specialized workers.

**Comment by eric-gonzalez-tfs** [comment]
Thank you for the feedback!

I ended up calling `boss.cancel` which appears to accomplish this. The job being in a "cancelled" state also lets us differentiate between a job that was completed, failed and cancelled (likely due to a fatal error).
