### ISSUE TITLE
Would you be open to supporting a conn pool object during initialization (instead of conn string)

### ISSUE THREAD

**Issue by kevbook** [timgit/pg-boss#518]
This enables us to use this in serverless environments. Below uses websockets internally

- https://neon.tech/blog/quicker-serverless-postgres
- https://neon.tech/docs/serverless/serverless-driver

```js
import { Pool } from '@neondatabase/serverless';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const posts = await pool.query('SELECT * FROM posts WHERE id =$1', [postId]);
pool.end();
```

Basically, it kind of bypasses `.db.js`

**Comment by kevbook** [comment]
Just in case, that's too much of a change, node `postgres` driver works for serverless too, especially for cloudflare workers. I think this would "mostly" be a drop-in replacement

- https://github.com/porsager/postgres
- https://developers.cloudflare.com/workers/tutorials/postgres

**Comment by timgit** [comment]
The db prop in the constructor is for bypassing the internal driver. Have you tried this?

**Comment by kevbook** [comment]
Ah, that makes sense, this works locally. I'll test it on the edge 

```js
import { neon } from '@neondatabase/serverless';
import PgBoss from 'pg-boss';
import { Config } from '$config/config';

// Create a postgres client and ensure connection (send a ping)
const postgres = neon(Config.pgBoss.connString, {
  fullResults: true,
  fetchOptions: { priority: 'high' },
});

const boss = new PgBoss({
  application_name: Config.service.name,
  migrate: false,
  db: {
    executeSql: async function (text: string, values: any[]) {
      return postgres(text, values);
    },
  },
});

const id = await boss.send('help-me', { hello: 'world' });
console.log(`created job: ${id}`);
```
