### ISSUE TITLE
[docs] sinon mock of setIntermediate breaks subscribe

### ISSUE THREAD

**Issue by JulesAU** [timgit/pg-boss#62]
I just spent hours trying to figure out why job subscriptions weren't working when running in my mocha test harness.

Turns out my use of sinon to mock timers was interfering with the `setImmediate` call in Manager.

[Others have had this problem](https://github.com/sinonjs/sinon/issues/960) with sinon; obviously it's not a pg-boss issue, but might be worth putting in the docs to save someone else tearing their hair out in future :-)

Cheers

**Comment by timgit** [comment]
🤔 That's interesting.  Do you have an example of how others have "documented" this?  I see a couple issues linked from your linked issue, but I don't understand what you're proposing here.  How about I just close this issue like the other deps have and we're good?  😀

**Comment by JulesAU** [comment]
Yeah you're right. I've made the issue title more Google friendly; so hopefully if someone is having similar trouble they'll find this issue.

Closing :-)
