### ISSUE TITLE
Bug: job object returned by fetch doesn't have done() method.

### ISSUE THREAD

**Issue by robgraeber** [timgit/pg-boss#64]
Seems like job.done() is not defined when using the fetch function. For example:

```js
boss.fetch('queue_name').then(function(job) {  
  if (!job) return;
  job.done(); //done() is not a defined   
  return null;   
});   
```

As a workaround, I've been using boss.complete(job.id)

**Comment by timgit** [comment]
job.done() is a convenience callback only for the subscribe() api.  This is not a bug, since the intention behind fetch() is that you will also explicitly call complete() or fail().

**Comment by robgraeber** [comment]
Hmm okay, I think it's a bit weird having multiple job types but closing since it's expected.

**Comment by phips28** [comment]
@robgraeber why do you need multiple job types?

I just use one type "work" (or when I use staging+dev on one database then "work-dev") - I call it queue name.

Then in the job payload I have a field "jobName": "doSomething".
Then my subscribe() reads the payload and executes: `doSomething(payload)`

**Comment by robgraeber** [comment]
@phips28 not totally sure what you mean, I'm talking about the job object returned by fetch(). Where the subscribe callback passes `JobWithDoneCallback`, while fetch() passes `Job`. It's minor but counterintuitive enough that I thought it was a bug.

**Comment by phips28** [comment]
ohh sry, I thought you mean the name of the jobs with "job types"

forget what I said ;)
