### ISSUE TITLE
New index for performance improvement

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#72]
I tried some different indexes to improve our worker queries.
(they are currently the performance killer on our database 🙈 )

Current situation: We have ~4000 created jobs in our table with `startIn` set in the future.

EXPLAIN has cost of ~1770:
![screenshot_2018-04-06_21_35_43](https://user-images.githubusercontent.com/3694800/38451347-f5110e1c-39e2-11e8-85c0-aedca3cbbad1.png)

After creating this index, it was ~13:
👉 `CREATE INDEX job_name ON shard_01_pgboss.job (name);`

![screenshot_2018-04-06_21_35_58](https://user-images.githubusercontent.com/3694800/38451348-fe675cbe-39e2-11e8-80a8-8131d4b70ae7.png)

**A lot faster** 🎉

_Postgres decides itself what index to use to get the optimal performance, so if you only have 10 jobs in the table, it might not use the name index._

---

does anyone else have different index setups?

**Comment by timgit** [comment]
I feel like i dropped the ball on this.  :(  Thanks.  I'd like to know if adding name to the existing job_fetch index would also work as well.  

```sql
CREATE INDEX job_fetch ON ${schema}.job (name, priority desc, createdOn, id) WHERE state < '${states.active}'
```

**Comment by phips28** [comment]
ok I tested it:

without any new index:
![screenshot 2018-04-07 13 06 47](https://user-images.githubusercontent.com/3694800/38459898-ae548c2e-3a64-11e8-93cf-3d1e07c615ef.png)

with **job_name**: `CREATE INDEX job_name ON shard_01_pgboss.job (name);`
![screenshot 2018-04-07 13 06 50](https://user-images.githubusercontent.com/3694800/38459899-ae6fba80-3a64-11e8-88fd-0288889770b4.png)

with new **job_fetch**: `CREATE INDEX job_fetch ON ${schema}.job (name, priority desc, createdOn, id) WHERE state < '${states.active}'`
![screenshot 2018-04-07 13 06 56](https://user-images.githubusercontent.com/3694800/38459900-ae87b310-3a64-11e8-9043-0476429235f6.png)

In this case the job_name index was faster than the combined job_fetch index.
