### ISSUE TITLE
Poll: pgcrypto extension

### ISSUE THREAD

**Issue by timgit** [timgit/pg-boss#76]
For those of you watchers (or wanderers), would any of you take issue with or have constraints preventing the use of the pgcrypto extension for pgboss ilo uuid generation?

**Comment by terehov** [comment]
Nope, we use pgcrypto anyway 👍🏻

**Comment by pyros2097** [comment]
Is it possible to allow us to create the uuid for the job by passing the func or id as a parameter. You see there are some jobs which I would like to run only once like a migration job and it will have a unique id and and if another process tries to run that job with the same id it would abort based on the Job's uniqueness constraint.

**Comment by timgit** [comment]
@pyros2097, you can do unique jobs via the [singletonKey config](https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#unique-jobs)

**Comment by pyros2097** [comment]
Ohh..  :thinking: Didn't see that before. Thats exactly what I needed. Thanks @timgit . :cake:
