### ISSUE TITLE
Support for querying jobs table to prevent duplicate jobs

### ISSUE THREAD

**Issue by ranyefet** [timgit/pg-boss#8]
Hello,

This looks like a nice library.
My use case is the following, I like to schedule a single message every 24 hours for active users.
Meaning if user came to the app and did some action, I like to schedule a message that will be sent to the user in 24 hours.

But I only want to have a single schedule message for every user in a 24 hour duration.

I was thinking querying the jobs table before creating a job, but I wonder if there's a better way?

Thanks,
Ran.

**Comment by timgit** [comment]
Hey Ran.  Yes, you could use a combination of the delay and throttling configuration to do this, but in the process of writing a test for this use case, I discovered something in the throttling logic that would cause your use case to get 1 extra email.  So, for now, know that I intended for this use case to work, but give me a day or so to get a patch pushed to address it.

For example,

```js
pgboss.publish('userActionEmail', actionPayload, { startIn: '24 hours', singletonHours: 24});
```

**Comment by timgit** [comment]
Ran, I pushed 0.4.0 last night to address this.  Try the example config I posted above and let me know if it works or not.

Cheers!

**Comment by ranyefet** [comment]
@timgit Thanks for the quick update! I will try it 👍
