### ISSUE TITLE
Can't connect to db without username

### ISSUE THREAD

**Issue by melnikaite** [timgit/pg-boss#80]
```
new PgBoss({
     host: '127.0.0.1',
     user: undefined,
     password: undefined,
     database: 'db',
     schema: 'job_queue',
     poolSize: 5,
})
```
result:
`AssertionError [ERR_ASSERTION]: configuration assert: not enough database settings to connect `
expected:
connect to db using default username, like in `knex`

**Comment by timgit** [comment]
Yeah, I should relax the validation here, since the core pg driver can actually pull all of this out of environment variables.
