### ISSUE TITLE
Add id to subscribe for displaying which worker has the active job

### ISSUE THREAD

**Issue by jr14marquez** [timgit/pg-boss#85]
I have a few servers that i run pgboss on and would like details on which server is working on which jobs.  It would be great to allow me to pass an id or the hostname to subscribe so that when the job is switched from created to active it shows in the database who is working on the job.  From there i can poll the database gathering details/stats.  Something like the following would be great:

boss.subscribe(queue, hostname, someAsyncJobHandler);

**Comment by timgit** [comment]
Agreed 👍
