### ISSUE TITLE
Superuser permissions

### ISSUE THREAD

**Issue by timothyallan** [timgit/pg-boss#91]
First off, great library, thanks for putting it together!

The docs say that in order for the schema/tables to be created, the user needs create perms for the DB. My user has create granted for the DB, but when I roll over to the live site, I'm getting:

```
Error: QueueBoss Error! {
  "name": "error",
  "length": 165,
  "severity": "ERROR",
  "code": "42501",
  "hint": "Must be superuser to create this extension.",
  "file": "extension.c",
  "line": "809",
  "routine": "execute_extension_script"
}
```
I'm assuming that the db user needs more than just create in order to set up the initial stuff? I really don't want to make him a superuser on the live db, and I'd also like to keep things automated instead of using the `PgBoss.getConstructionPlans()` method.

**Comment by timgit** [comment]
I introduced pgcrypto as a dependency in 3.0 and unintentionally broke that requirement.  For now,  you will need to bundle the extension creation along with your database while I think about plan B.

```sql
CREATE EXTENSION IF NOT EXISTS pgcrypto;
```

**Comment by timgit** [comment]
I'm going to have to issue a patch to pull this command out of the schema creation and migration.

**Comment by timothyallan** [comment]
Docs look good, crystal clear now 👍

**Comment by esatterwhite** [comment]
It doesn't seem like it should be an action of the project to try to create a schema and install an extension.  I would much rather have that be a part of a deployment / provisioning process than a run time dependency. 
run the application as a superuser in production as a requirement is a bit of a deal breaker.

you can always check if pgcrypto is installed and throw an error if it doesn't exist

```sql
-- returns TRUE / FALSE
SELECT EXISTS (
  SELECT 1
  FROM pg_extension
  WHERE extname = 'pgcrypto'
)
```
or 

```sql
-- Just Throws an error if not installed
SELECT GEN_RANDOM_UUID()
```

either of these would tell you if the extension were installed.

**Comment by esatterwhite** [comment]
If all you need is a random value as an ID, you don't really need pgcrypto for this.

```sql
SELECT
  MD5( 
    ARRAY_TO_STRING(
      ARRAY(
        SELECT chr((48 + round(random() * 59)) :: INT) 
        FROM generate_series(1, 15)
      ), ''
    )
  );
```
`e2cb3f38d61d87cc53007d14862dbfa8`

**Comment by timgit** [comment]
I agree with you on running as superuser in prod.  It's not recommended, and I don't run pg-boss that way, either. While I don't have language that says "don't do this" in the docs, I do have this constraint documented and it's mentioned as an installation dependency, not a run-time dependency.

https://github.com/timgit/pg-boss/blob/master/docs/usage.md#database-installation

In regards to creating the schema, if you're objecting to the package maintaining it's own storage, you  can opt out of that as well using the static exports for schema creation and migration.  It's a bit more overhead for maintenance, but it does remove all schema modifications from the runtime.

**Comment by esatterwhite** [comment]
How would one do that? Not call the `start` function? The start functions calls `plans.create` which calls a series of functions which [don't appear to be exported](https://github.com/timgit/pg-boss/blob/master/src/plans.js#L33)

call `pgboss.connect` then `pgboss.migrate`?

**Comment by timgit** [comment]
`getConstructionPlans()` is one example from https://github.com/timgit/pg-boss/blob/master/docs/usage.md#static-functions
