### ISSUE TITLE
Job retries?

### ISSUE THREAD

**Issue by djvs** [timgit/pg-boss#96]
My job handler function is an async function.  Based on the docs, I assumed that by (a) adding non-zero retryLimit and retryDelay in the enqueue options, and (b) returning undefined from my job handler function, and not executing `job.done(non_error_value)` or `job.done(new Error('foobar'))`, would automatically enqueue a retry.  But this seems to not be the behavior.  Any help here?

**Comment by djvs** [comment]
Also what is the unit for "retry delay"?  Which, by the way, doesn't seem to be stored in the database, unless it's stored as one of these other fields?

**Comment by djvs** [comment]
Been fiddling with this for hours - tried seemingly every variation of returning nothing or an error, calling job.done or not with true/false/an error, etc.  Stumped.  Feel like something is broken unless I missed a case somehow.

**Comment by djvs** [comment]
Withdrawn - I was using 2.5.1 still.

**Comment by timgit** [comment]
Glad you resolved that.  In response to your first post, in point b), you should never return from an async function in order to fail a job.  returning from an async function is always considered a resolve(returned value), not a reject().
