### ISSUE TITLE
Multiple onComplete notification for the same job

### ISSUE THREAD

**Issue by tonyxiao** [timgit/pg-boss#97]
It seems that onComplete uses the same logic as subscribe, meaning there can only ever be one subscriber per job. How would you recommend broadcasting job completion event to multiple subscribers?

**Comment by timgit** [comment]
The entire system is designed with the idea of "at most once" semantics.  I'm not sure what your use case is, but you could set up a separate job per downstream consumer, then just have the first onComplete publish all of them simultaneously.
